Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2022-10, with the labels that each got.

#313 Canary Release (canary)
  .changeset/pre.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: 🐥 canary release

#321 DB-4018: remove workspace based dev dependencies for deployment
  pnpm-lock.yaml
  web/package.json
Labels: documentation

#323 Try adding nvmrc to work around platform bug
  web/.nvmrc
Labels: documentation

#322 DB-3969: Update seo.jsx with new Gatsby Head API
  .changeset/dull-clouds-sparkle.md
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/gatsby-config.js
  starters/gatsby-wordpress-starter/gatsby-ssr.js
  starters/gatsby-wordpress-starter/package.json
  starters/gatsby-wordpress-starter/src/components/seo.jsx
  starters/gatsby-wordpress-starter/src/pages/404.jsx
  starters/gatsby-wordpress-starter/src/templates/index.jsx
  starters/gatsby-wordpress-starter/src/templates/page.jsx
  starters/gatsby-wordpress-starter/src/templates/pagesIndex.jsx
  starters/gatsby-wordpress-starter/src/templates/post.jsx
  starters/gatsby-wordpress-starter/src/templates/postsIndex.jsx
Labels: gatsby-wordpress

#324 DB-3618: Implement `nextjs-kit` components
  .changeset/hot-frogs-wash.md
  starters/next-wordpress-starter/__tests__/data/pageData.json
  starters/next-wordpress-starter/__tests__/data/postData.json
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/auth-api.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/example-index.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/homepage.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pages.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagination.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/posts.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/ssg-isr-example.test.jsx.snap
  starters/next-wordpress-starter/components/footer.jsx
  starters/next-wordpress-starter/components/grid.jsx
  starters/next-wordpress-starter/components/header.jsx
  starters/next-wordpress-starter/components/layout.jsx
  starters/next-wordpress-starter/components/page.jsx
  starters/next-wordpress-starter/components/post.jsx
  starters/next-wordpress-starter/pages/examples/ssg-isr.jsx
  starters/next-wordpress-starter/pages/index.jsx
  starters/next-wordpress-starter/pages/pages/[uri].jsx
  starters/next-wordpress-starter/pages/pages/index.jsx
  starters/next-wordpress-starter/pages/posts/[slug].jsx
  starters/next-wordpress-starter/pages/posts/index.jsx
Labels: next-wordpress

#320 DB-3186: Add Pagination To Page and Post List
  .changeset/dry-apples-rule.md
  packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/paginator.test.tsx.snap
  packages/nextjs-kit/src/components/paginator.tsx
  starters/next-drupal-starter/__tests__/__snapshots__/default/pagination.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/pagination.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pages.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagination.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/posts.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/pages.test.jsx
  starters/next-wordpress-starter/__tests__/snapshotTests/posts.test.jsx
  starters/next-wordpress-starter/components/grid.jsx
  starters/next-wordpress-starter/lib/Pages.js
  starters/next-wordpress-starter/lib/Posts.js
  starters/next-wordpress-starter/lib/WordPressClient.js
  starters/next-wordpress-starter/pages/pages/[uri].jsx
  starters/next-wordpress-starter/pages/pages/index.jsx
  starters/next-wordpress-starter/pages/posts/[slug].jsx
  starters/next-wordpress-starter/pages/posts/index.jsx
Labels: next-wordpress

#329 Remove reference to Drupal in next-wp starter
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/example-index.test.jsx.snap
  starters/next-wordpress-starter/pages/examples/index.jsx
Labels: next-wordpress

#330 DB-3186: Update query parameters
  .changeset/late-dryers-collect.md
  starters/next-wordpress-starter/lib/Pages.js
  starters/next-wordpress-starter/lib/Posts.js
  starters/next-wordpress-starter/pages/examples/ssg-isr.jsx
  starters/next-wordpress-starter/pages/index.jsx
  starters/next-wordpress-starter/pages/pages/index.jsx
  starters/next-wordpress-starter/pages/posts/index.jsx
Labels: next-wordpress

#331 Add missing changesets for sprint 33 release
  .changeset/late-pens-arrive.md
Labels: 🐥 canary release

#334 Sprint 33 exit pre release mode
  .changeset/pre.json
Labels: release

#339 Enter pre-release mode for sprint 34
  .changeset/pre.json
Labels: release

#300 DB-4100: [gatsby-wp-starter] Inject pathprefix
  .changeset/late-donuts-love.md
  starters/gatsby-wordpress-starter/.env.example
  starters/gatsby-wordpress-starter/gatsby-config.js
  starters/gatsby-wordpress-starter/src/components/post.jsx
  starters/gatsby-wordpress-starter/src/templates/index.jsx
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/setting-path-prefix.md
Labels: gatsby-wordpress

#340 DB-2834: add post-install script
  package.json
  scripts/post-install
Labels: decoupled-kit

#326 DB-3657: Block Editor Video Styles
  .changeset/kind-tables-count.md
  packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Video.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts
Labels: wordpress-kit

#343 DB-2834: Automatically Husky Install
  .husky/pre-commit
Labels: decoupled-kit

#342 DB-3768: [gatsby-wordpress-starter] Add snapshot tests
  .changeset/new-sloths-attend.md
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/README.md
  starters/gatsby-wordpress-starter/__tests__/data/allWpPost.json
  starters/gatsby-wordpress-starter/__tests__/data/generalSettings.json
  starters/gatsby-wordpress-starter/__tests__/data/pages.json
  starters/gatsby-wordpress-starter/__tests__/data/twitter.json
  starters/gatsby-wordpress-starter/__tests__/data/wpMenu.json
  starters/gatsby-wordpress-starter/__tests__/setupFile.js
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/homepage.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/page.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagesIndex.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/post.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/postsIndex.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/homepage.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/page.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/pagesIndex.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/post.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/postsIndex.test.jsx
  starters/gatsby-wordpress-starter/package.json
  starters/gatsby-wordpress-starter/src/components/post.jsx
  starters/gatsby-wordpress-starter/src/components/seo.jsx
  starters/gatsby-wordpress-starter/src/templates/page.jsx
  starters/gatsby-wordpress-starter/vite.config.js
Labels: gatsby-wordpress

#328 DB-3622: Implement `nextjs-kit` components into drupal starter
  .changeset/gorgeous-tomatoes-fetch.md
  .changeset/three-days-judge.md
  packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/recipe.test.tsx.snap
  packages/nextjs-kit/src/components/recipe.tsx
  starters/next-drupal-starter/__tests__/__snapshots__/default/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/articles.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/auth-api.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/examples-index.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/homepage.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/pages.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/pagination.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/recipes.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/ssr-isr-example.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/articles.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/auth-api.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/examples-index.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/homepage.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/pages.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/pagination.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/recipes.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/ssr-isr-example.test.jsx.snap
  starters/next-drupal-starter/__tests__/setupFile.js
  starters/next-drupal-starter/components/article.jsx
  starters/next-drupal-starter/components/footer.jsx
  starters/next-drupal-starter/components/grid.jsx
  starters/next-drupal-starter/components/header.jsx
  starters/next-drupal-starter/components/layout.jsx
  starters/next-drupal-starter/components/recipe.jsx
  starters/next-drupal-starter/pages/[...alias].jsx
  starters/next-drupal-starter/pages/articles/[...slug].jsx
  starters/next-drupal-starter/pages/articles/index.jsx
  starters/next-drupal-starter/pages/examples/ssg-isr.jsx
  starters/next-drupal-starter/pages/index.jsx
  starters/next-drupal-starter/pages/recipes/[...slug].jsx
  starters/next-drupal-starter/pages/recipes/index.jsx
Labels: next-drupal

#347 DB-3768: attempt to add the trigger-e2e workflow prior to canary split
  .github/templates/trigger-e2e.yml.template
  .github/workflows/canary-sites-split.yml
Labels: ci/cd

#348 DB-3768: prefix github workspace to path
  .github/workflows/canary-sites-split.yml
Labels: ci/cd

#349 DB-3768: ensure parent directory is created
  .github/workflows/canary-sites-split.yml
Labels: ci/cd

#344 DB-4234: [next-drupal-starter] inject upload path
  .changeset/friendly-rocks-speak.md
  starters/next-drupal-starter/.env.example
  starters/next-drupal-starter/next.config.js
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/setting-path-prefix.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/setting-cache-control-header.md
  web/docs/Frontend Starters/Next.js/setting-base-path.md
  web/docs/Frontend Starters/Next.js/static-vs-dynamic.md
Labels: documentation, next-drupal

#346 DB-4233: [next-wordpress-starter] Inject base path
  .changeset/small-llamas-smile.md
  starters/next-wordpress-starter/.env.example
  starters/next-wordpress-starter/next.config.js
  starters/next-wordpress-starter/pages/404.jsx
Labels: next-wordpress

#351 DB-2625: [next-drupal-starter] Document common issues
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/troubleshooting.md
Labels: documentation

#350 modified line 93 pnpm build:docs && pnpm start:docs to pnpm generate-…
  README.md
Labels: documentation, decoupled-kit

#354 DB-2624: Document gatsby-wp common trobuleshooting
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/troubleshooting.md
Labels: documentation

#355 DB-4534: [next-wordpress-starter] Add doc troubleshooting docs
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/troubleshooting.md
Labels: documentation

#356 DB-2366: Add CODEOWNERS file.
  CODEOWNERS
Labels: documentation

#357 DB-1504: Gatsby Pagination Example
  .changeset/long-apricots-taste.md
  .changeset/polite-lizards-kick.md
  .changeset/smart-eyes-rhyme.md
  packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/paginator.test.tsx.snap
  packages/nextjs-kit/src/components/paginator.tsx
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/__tests__/data/examplePaginationData.json
  starters/gatsby-wordpress-starter/__tests__/setupFile.js
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/homepage.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/page.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagesIndex.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagination.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/post.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/postsIndex.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/homepage.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/pagination.test.jsx
  starters/gatsby-wordpress-starter/gatsby-node.js
  starters/gatsby-wordpress-starter/lib/postsPagination.js
  starters/gatsby-wordpress-starter/package.json
  starters/gatsby-wordpress-starter/src/components/layout.jsx
  starters/gatsby-wordpress-starter/src/components/paginator.jsx
  starters/gatsby-wordpress-starter/src/templates/examples.jsx
  starters/gatsby-wordpress-starter/src/templates/pagination.jsx
  starters/next-drupal-starter/__tests__/__snapshots__/default/pagination.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/pagination.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagination.test.jsx.snap
Labels: gatsby-wordpress

#360 Update docs site url
  web/docusaurus.config.js
Labels: documentation

#359 Canary Release (canary)
  .changeset/pre.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
  web/docs/Packages/wordpress-kit/classes/lib_tailwindcssPlugin_utilities_Base.BaseUtilities.md
  web/docs/Packages/wordpress-kit/modules/lib_tailwindcssPlugin_components_shared_Alignment.md
  web/docs/Packages/wordpress-kit/modules/lib_tailwindcssPlugin_utilities_Base.md
Labels: 🐥 canary release

#364 Sprint 34 - exit prerelease mode
  .changeset/pre.json
Labels: release

#367 Update versions
  .changeset/friendly-rocks-speak.md
  .changeset/gorgeous-tomatoes-fetch.md
  .changeset/hungry-gifts-cross.md
  .changeset/kind-tables-count.md
  .changeset/late-donuts-love.md
  .changeset/long-apricots-taste.md
  .changeset/new-sloths-attend.md
  .changeset/polite-lizards-kick.md
  .changeset/pre.json
  .changeset/serious-trainers-doubt.md
  .changeset/small-llamas-smile.md
  .changeset/smart-eyes-rhyme.md
  .changeset/three-days-judge.md
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#370 Sprint 35 - enter prerelease
  .changeset/pre.json
Labels: release

#361 DB-1526: Add Pagination to Page and Post Routes
  .changeset/new-teachers-drum.md
  starters/gatsby-wordpress-starter/__tests__/data/allWpPost.json
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/homepage.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/page.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagesIndex.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagination.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/postsIndex.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/homepage.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/page.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/pagesIndex.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/pagination.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/post.test.jsx
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/postsIndex.test.jsx
  starters/gatsby-wordpress-starter/gatsby-node.js
  starters/gatsby-wordpress-starter/src/components/grid.jsx
  starters/gatsby-wordpress-starter/src/components/paginator.jsx
  starters/gatsby-wordpress-starter/src/templates/index.jsx
  starters/gatsby-wordpress-starter/src/templates/pagesIndex.jsx
  starters/gatsby-wordpress-starter/src/templates/postsIndex.jsx
Labels: gatsby-wordpress

#375 DB-4562: Gatsby 404 page styles
  .changeset/happy-eggs-breathe.md
  starters/gatsby-wordpress-starter/src/pages/404.jsx
Labels: gatsby-wordpress
