Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2022-12, with the labels that each got.

#424 DB-3832: Document surrogate key based cache purging
  package.json
  pnpm-lock.yaml
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
  web/docusaurus.config.js
  web/package.json
Labels: documentation, decoupled-kit

#428 Fix gatsby dev mode, use pnpm cache in github action
  .changeset/slow-apples-hunt.md
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
  package.json
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/package.json
Labels: bugfix

#429 Update node-setup version to v3
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
Labels: bugfix

#432 Update release workflows to use pnpm/action-setp
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd, bugfix

#433 regenerate lockfile
  .changeset/warm-fireants-push.md
  .npmrc
  package.json
  packages/cms-kit/package.json
  packages/drupal-kit/package.json
  packages/nextjs-kit/package.json
  packages/nextjs-kit/tsconfig.json
  packages/nextjs-kit/vite.config.js
  packages/wordpress-kit/package.json
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/package.json
  web/package.json
Labels: decoupled-kit, dependencies, bugfix, nextjs-kit

#430 DB-4072: handle singular content type naming in next-wordpress preview
  .changeset/eighty-news-itch.md
  starters/next-wordpress-starter/pages/api/preview.js
Labels: next-wordpress

#437 DB-4451: Document Additional Envars
  .changeset/olive-cars-repeat.md
  starters/next-wordpress-starter/.env.example
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-environment-variables.md
Labels: next-wordpress

#436 DB-4893: Ensure gatsby-source-wordpress is on latest version
  .changeset/lemon-rats-obey.md
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/package.json
Labels: gatsby-wordpress, bugfix

#440 Sprint 37 exit prerelease mode
  .changeset/pre.json
Labels: release

#443 Update versions
  .changeset/big-zebras-speak.md
  .changeset/clean-fireants-beam.md
  .changeset/eighty-news-itch.md
  .changeset/fluffy-carrots-tell.md
  .changeset/lemon-rats-obey.md
  .changeset/olive-cars-repeat.md
  .changeset/perfect-hornets-invent.md
  .changeset/pre.json
  .changeset/slow-apples-hunt.md
  .changeset/soft-experts-deliver.md
  .changeset/spotty-weeks-fail.md
  .changeset/swift-chairs-repair.md
  .changeset/unlucky-zoos-jam.md
  .changeset/warm-fireants-push.md
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#444 Sprint 38 - Backmerge main -> canary
  .changeset/big-zebras-speak.md
  .changeset/clean-fireants-beam.md
  .changeset/eighty-news-itch.md
  .changeset/fluffy-carrots-tell.md
  .changeset/lemon-rats-obey.md
  .changeset/olive-cars-repeat.md
  .changeset/perfect-hornets-invent.md
  .changeset/pre.json
  .changeset/slow-apples-hunt.md
  .changeset/soft-experts-deliver.md
  .changeset/spotty-weeks-fail.md
  .changeset/swift-chairs-repair.md
  .changeset/unlucky-zoos-jam.md
  .changeset/warm-fireants-push.md
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#445 Sprint 38 enter prerelease mode
  .changeset/pre.json
Labels: release

#439 DB-4834: Set IS_LIVE_ENVIRONMENT
  .changeset/light-colts-bake.md
  starters/next-drupal-starter/.env.example
  starters/next-drupal-starter/next.config.js
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/setting-environment-variables.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-environment-variables.md
Labels: next-drupal

#449 DB-2845: Support Inline Images In Drupal Body Field
  .changeset/odd-eels-grow.md
  starters/next-drupal-starter/__tests__/__snapshots__/default/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/pages.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/pages.test.jsx.snap
  starters/next-drupal-starter/pages/[...alias].jsx
  starters/next-drupal-starter/pages/pages/[...alias].jsx
Labels: next-drupal

#448 DB-4836: Gatsby Set IS_LIVE_ENVIRONMENT
  .changeset/forty-dragons-tell.md
  starters/gatsby-wordpress-starter/.env.example
  starters/gatsby-wordpress-starter/gatsby-config.js
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/setting-environment-variables.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/setting-environment-variables.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-environment-variables.md
Labels: gatsby-wordpress

#450 DB-4953: [docs] Add implementing-preview to next+wp docs
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/implementing-preview.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-cache-control-header.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/styling-configuration.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/troubleshooting.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/your-first-customization.md
Labels: documentation

#446 DB-4935: Fix preview when content has no alias set in Drupal
  .changeset/brown-oranges-reflect.md
  starters/next-drupal-starter/pages/api/preview.js
Labels: next-drupal, bugfix

#447 Canary Release (canary)
  .changeset/pre.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
Labels: 🐥 canary release

#451 DB-883: Update surrogate key headers
  .changeset/angry-rules-knock.md
  .changeset/eight-waves-behave.md
  .changeset/large-donuts-mix.md
  packages/cms-kit/src/utils/setSurrogateKeyHeader.ts
  packages/drupal-kit/src/lib/defaultFetch.ts
  packages/wordpress-kit/__mocks__/server/basicPostsQuery.ts
  packages/wordpress-kit/src/lib/graphqlClient/GraphqlClientFactory.ts
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
Labels: documentation, drupal-kit, wordpress-kit, cms-kit

#452 DB-4935: Error if previewing a draft
  .changeset/poor-ducks-decide.md
  starters/next-drupal-starter/lib/getPreview.js
  starters/next-drupal-starter/pages/api/preview.js
Labels: next-drupal

#454 DB-4395: [docs] Add doc regarding limitation of previewing drafts in Drupal
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/implementing-preview.md
Labels: documentation

#455 Exit pre-release mode for sprint 38
  .changeset/pre.json
Labels: release

#457 Sprint 38 Release canary -> main
  .changeset/angry-rules-knock.md
  .changeset/brown-oranges-reflect.md
  .changeset/eight-waves-behave.md
  .changeset/forty-dragons-tell.md
  .changeset/large-donuts-mix.md
  .changeset/light-colts-bake.md
  .changeset/odd-eels-grow.md
  .changeset/poor-ducks-decide.md
  .changeset/pre.json
  .circleci/config.yml
  .github/workflows/canary-release.yml
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/cms-kit/src/utils/setSurrogateKeyHeader.ts
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/drupal-kit/src/lib/defaultFetch.ts
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/__mocks__/server/basicPostsQuery.ts
  packages/wordpress-kit/package.json
  packages/wordpress-kit/src/lib/graphqlClient/GraphqlClientFactory.ts
  starters/gatsby-wordpress-starter/.env.example
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/gatsby-config.js
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/.env.example
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/__tests__/__snapshots__/default/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/pages.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/pages.test.jsx.snap
  starters/next-drupal-starter/lib/getPreview.js
  starters/next-drupal-starter/next.config.js
  starters/next-drupal-starter/package.json
  starters/next-drupal-starter/pages/[...alias].jsx
  starters/next-drupal-starter/pages/api/preview.js
  starters/next-drupal-starter/pages/pages/[...alias].jsx
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/setting-environment-variables.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/implementing-preview.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/setting-environment-variables.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/implementing-preview.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-cache-control-header.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-environment-variables.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/styling-configuration.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/troubleshooting.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/your-first-customization.md
Labels: release

#459 Sprint 38 - backmerge main -> canary
  .changeset/angry-rules-knock.md
  .changeset/brown-oranges-reflect.md
  .changeset/eight-waves-behave.md
  .changeset/forty-dragons-tell.md
  .changeset/large-donuts-mix.md
  .changeset/light-colts-bake.md
  .changeset/odd-eels-grow.md
  .changeset/poor-ducks-decide.md
  .changeset/pre.json
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#460 Enter pre-release for sprint 39
  .changeset/pre.json
Labels: release
