Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2022-11, with the labels that each got.

#376 DB-4066: Block spacer styles
  .changeset/ninety-roses-jog.md
  packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Spacer.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts
Labels: wordpress-kit

#374 DB-4593: Add with-commit script, refactor some GH Actions
  .github/scripts/with-commit.sh
  .github/workflows/canary-release.yml
  .github/workflows/canary-repo-split.yml
  .github/workflows/main-release.yml
  .github/workflows/main-repo-split.yml
  .github/workflows/release-job.yml
Labels: decoupled-kit, ci/cd

#379 DB-4060: Block Editor Alignment Options
  .changeset/four-wolves-chew.md
  packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/contentWithImage.test.tsx.snap
  packages/nextjs-kit/src/components/contentWithImage.tsx
  starters/next-drupal-starter/__tests__/__snapshots__/default/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/articles.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/articles.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pages.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/posts.test.jsx.snap
Labels: nextjs-kit

#378 DB-4060: Block Editor Alignment Options
  .changeset/brown-eels-tap.md
  packages/wordpress-kit/src/lib/tailwindcssPlugin/utilities/Base.ts
Labels: wordpress-kit

#381 Revert DB-4593
  .github/scripts/with-commit.sh
  .github/workflows/canary-release.yml
  .github/workflows/canary-sites-split.yml
  .github/workflows/main-release.yml
  .github/workflows/release-and-split.yml
  .github/workflows/release-job.yml
Labels: ci/cd

#380 DB-4065: Block separator styles
  .changeset/hungry-roses-destroy.md
  packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Separator.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts
Labels: wordpress-kit

#372 Canary Release (canary)
  .changeset/pre.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
  web/docs/Packages/wordpress-kit/modules/lib_tailwindcssPlugin_components_Separator.md
  web/docs/Packages/wordpress-kit/modules/lib_tailwindcssPlugin_components_Spacer.md
Labels: 🐥 canary release

#382 DB-4463: [docs] How to Use Default (non-composer) WP Upstream with Starter Kits
  .changeset/dull-keys-smoke.md
  .changeset/weak-weeks-notice.md
  starters/gatsby-wordpress-starter/src/components/footer.jsx
  starters/next-wordpress-starter/__tests__/snapshotTests/pages.test.jsx
  starters/next-wordpress-starter/__tests__/snapshotTests/posts.test.jsx
  starters/next-wordpress-starter/lib/Menus.js
  starters/next-wordpress-starter/lib/Pages.js
  starters/next-wordpress-starter/lib/Posts.js
  starters/next-wordpress-starter/pages/pages/[...uri].jsx
  starters/next-wordpress-starter/pages/posts/[...slug].jsx
  web/docs/Backend Starters/Decoupled WordPress/configuring-existing-project.md
Labels: documentation, gatsby-wordpress, next-wordpress

#383 DB-4063: Block editor column styles
  .changeset/wicked-dogs-report.md
  packages/wordpress-kit/src/lib/tailwindcssPlugin/Config.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Columns.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/index.ts
  packages/wordpress-kit/src/lib/tailwindcssPlugin/index.ts
Labels: wordpress-kit

#386 DB-4593: [ci] Add with-commit script, refactor some GH actions
  .github/scripts/with-commit.sh
  .github/workflows/canary-release.yml
  .github/workflows/canary-repo-split.yml
  .github/workflows/main-release.yml
  .github/workflows/main-repo-split.yml
  .github/workflows/release-job.yml
Labels: ci/cd

#387 DB-4065: Block separator style adjustment
  .changeset/light-carrots-joke.md
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Separator.ts
Labels: wordpress-kit

#384 Canary Release (canary)
  .changeset/pre.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
  web/docs/Packages/wordpress-kit/modules/lib_tailwindcssPlugin_components_Columns.md
Labels: 🐥 canary release

#390 Exit prerelease for sprint 35
  .changeset/pre.json
Labels: release

#393 Sprint 35 Backmerge main -> canary
  .changeset/afraid-dingos-dream.md
  .changeset/brown-eels-tap.md
  .changeset/dull-keys-smoke.md
  .changeset/four-wolves-chew.md
  .changeset/happy-eggs-breathe.md
  .changeset/hungry-roses-destroy.md
  .changeset/light-carrots-joke.md
  .changeset/new-teachers-drum.md
  .changeset/ninety-roses-jog.md
  .changeset/olive-jeans-begin.md
  .changeset/pre.json
  .changeset/sweet-pants-eat.md
  .changeset/tender-students-occur.md
  .changeset/weak-weeks-notice.md
  .changeset/wicked-dogs-report.md
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#394 Enter prerelease mode for sprint 36
  .changeset/pre.json
Labels: release

#397 DB-3674: Refactor Stores
  .changeset/healthy-seas-hide.md
  .changeset/smooth-apes-rescue.md
  packages/drupal-kit/package.json
  packages/drupal-kit/src/lib/PantheonDrupalState.ts
  pnpm-lock.yaml
  starters/next-drupal-starter/__tests__/getPaths.test.js
  starters/next-drupal-starter/__tests__/getPreview.test.js
  starters/next-drupal-starter/lib/getPaths.js
  starters/next-drupal-starter/lib/getPreview.js
  starters/next-drupal-starter/lib/stores.js
  starters/next-drupal-starter/pages/[...alias].jsx
  starters/next-drupal-starter/pages/api/preview.js
  starters/next-drupal-starter/pages/articles/[...slug].jsx
  starters/next-drupal-starter/pages/articles/index.jsx
  starters/next-drupal-starter/pages/examples/auth-api.jsx
  starters/next-drupal-starter/pages/examples/index.jsx
  starters/next-drupal-starter/pages/examples/pagination/[[...page]].jsx
  starters/next-drupal-starter/pages/examples/ssg-isr.jsx
  starters/next-drupal-starter/pages/index.jsx
  starters/next-drupal-starter/pages/pages/[...alias].jsx
  starters/next-drupal-starter/pages/pages/index.jsx
  starters/next-drupal-starter/pages/recipes/[...slug].jsx
  starters/next-drupal-starter/pages/recipes/index.jsx
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/implementing-preview.md
Labels: next-drupal, drupal-kit

#398 DB-3185: Adds preview api route
  .changeset/hot-snails-move.md
  starters/next-wordpress-starter/.env.example
  starters/next-wordpress-starter/__tests__/getAuthCredentials.test.js
  starters/next-wordpress-starter/lib/Pages.js
  starters/next-wordpress-starter/lib/Posts.js
  starters/next-wordpress-starter/lib/WordPressClient.js
  starters/next-wordpress-starter/pages/500.jsx
  starters/next-wordpress-starter/pages/api/preview.js
  starters/next-wordpress-starter/pages/pages/[...uri].jsx
  starters/next-wordpress-starter/pages/posts/[...slug].jsx
Labels: next-wordpress

#402 DB-2839: Updating Theming
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/styling-configuration.md
Labels: documentation

#403 DB-2840: Updating Theming Docs
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/styling-configuration.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/styling-configuration.md
Labels: documentation

#400 Canary Release (canary)
  .changeset/pre.json
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
  web/docs/Packages/wordpress-kit/classes/lib_graphqlClient_GraphqlClientFactory.default.md
  web/docs/Packages/wordpress-kit/modules/lib_graphqlClient_GraphqlClientFactory.md
Labels: 🐥 canary release

#405 DB-1406: Gatsby Auth API Demo
  .changeset/tiny-carpets-shave.md
  starters/gatsby-wordpress-starter/.env.example
  starters/gatsby-wordpress-starter/README.md
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/authApi.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/authApi.test.jsx
  starters/gatsby-wordpress-starter/gatsby-node.js
  starters/gatsby-wordpress-starter/lib/privatePosts.js
  starters/gatsby-wordpress-starter/src/templates/authApi.jsx
  starters/gatsby-wordpress-starter/src/templates/examples.jsx
Labels: gatsby-wordpress

#404 DB-3246: Add decoupled kit repo overview doc
  web/docs/Backend Starters/_category.json
  web/docs/Packages/_category.json
  web/docs/contributing.md
  web/docs/decoupled-kit-overview.md
  web/docusaurus.config.js
  web/src/pages/index.js
Labels: documentation

#408 [gatsby-wordpress] Fix URL for graphql client if WPGRAPHQL_URL is not set
  .changeset/breezy-mangos-smell.md
  starters/gatsby-wordpress-starter/gatsby-config.js
  starters/gatsby-wordpress-starter/lib/privatePosts.js
Labels: gatsby-wordpress, bugfix

#410 Exit prerelease mode - Sprint 36
  .changeset/pre.json
Labels: release

#415 fix: remove workspace from cms-kit version
  packages/drupal-kit/package.json
  packages/wordpress-kit/package.json
Labels: bugfix, drupal-kit, wordpress-kit

#417 Enter prerelease mode for sprint 37
  .changeset/pre.json
Labels: release

#401 DB-2874: Create Preview Error Route
  .changeset/spotty-weeks-fail.md
  starters/next-drupal-starter/pages/api/clear-preview.js
  starters/next-drupal-starter/pages/api/preview.js
  starters/next-drupal-starter/pages/preview-error/[[...alias]].jsx
Labels: next-drupal

#414 DB-4067: Preview Banner
  .changeset/clean-fireants-beam.md
  .changeset/swift-chairs-repair.md
  .changeset/unlucky-zoos-jam.md
  packages/nextjs-kit/src/components/index.ts
  packages/nextjs-kit/src/components/previewRibbon.tsx
  starters/next-drupal-starter/components/layout.jsx
  starters/next-drupal-starter/components/preview-ribbon.jsx
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/auth-api.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/example-index.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/homepage.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pages.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagination.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/posts.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/ssg-isr-example.test.jsx.snap
  starters/next-wordpress-starter/components/layout.jsx
  starters/next-wordpress-starter/pages/api/clear-preview.js
  starters/next-wordpress-starter/pages/pages/[...uri].jsx
  starters/next-wordpress-starter/pages/posts/[...slug].jsx
Labels: next-drupal, next-wordpress, nextjs-kit

#421 Tweaking the meta
  web/docusaurus.config.js
  web/src/pages/index.js
Labels: documentation

#422 DB-4829: Images Can Scale Past Native Width and Height
  .changeset/big-zebras-speak.md
  packages/wordpress-kit/src/lib/tailwindcssPlugin/components/Image.ts
Labels: wordpress-kit

#420 Remove extra line
  web/docs/decoupled-kit-overview.md
Labels: documentation

#419 DB-4487: use pnpm ignoreCves to make our nightly audit useable again
  .circleci/config.yml
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
  README.md
  package.json
  pnpm-lock.yaml
  web/docs/contributing.md
Labels: documentation, decoupled-kit, ci/cd
