Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2022-06, with the labels that each got.

#112 DB-2818: Bump package-lock on automated release
  .github/workflows/release-and-split.yml
  .github/workflows/release.yml
  .github/workflows/update-lockfiles.sh
Labels: decoupled-kit, ci/cd

#119 DB-2818: Fix GH action
  .github/workflows/release-and-split.yml
Labels: decoupled-kit, ci/cd, bugfix

#122 DB-2818: Run packages_split job after version
  .github/workflows/release-and-split.yml
Labels: decoupled-kit, ci/cd, bugfix

#126 DB-2566: Update example auth api
  .changeset/quick-guests-marry.md
  starters/next-drupal-starter/pages/examples/auth-api.js
Labels: next-drupal

#128 Drupal state upgrade
  .changeset/dirty-geese-buy.md
  packages/drupal-kit/package.json
  pnpm-lock.yaml
  starters/next-drupal-starter/pages/articles/[...slug].js
  starters/next-drupal-starter/pages/pages/[...alias].js
  starters/next-drupal-starter/pages/recipes/[...slug].js
Labels: next-drupal, dependencies, drupal-kit

#127 DB-2793: Add note and options to reduce concurrency for gatsby-source-wordpress
  starters/gatsby-wordpress-starter/gatsby-config.js
Labels: gatsby-wordpress

#130 DB-2235: Remove `next-absolute-url`
  pnpm-lock.yaml
  starters/next-drupal-starter/package-lock.json
  starters/next-drupal-starter/package.json
Labels: next-drupal, dependencies

#124 DB-2864: Added additional doc for git hosts or CI services example flags.
  web/docs/Backend Starters/Decoupled Drupal/creating-new-project.md
  web/docs/Backend Starters/Decoupled WordPress/creating-new-project.md
Labels: documentation

#129 DB-2295: Create helper for getStaticPaths
  .changeset/mighty-pianos-bow.md
  starters/next-drupal-starter/lib/getPaths.js
  starters/next-drupal-starter/pages/articles/[...slug].js
  starters/next-drupal-starter/pages/examples/auth-api.js
  starters/next-drupal-starter/pages/examples/pagination/[[...page]].js
  starters/next-drupal-starter/pages/pages/[...alias].js
  starters/next-drupal-starter/pages/pages/index.js
  starters/next-drupal-starter/pages/recipes/[...slug].js
  web/docs/Frontend Starters/Next Drupal/implementing-preview.md
Labels: next-drupal

#131 DB-1020: Create canary site for next-drupal-starter
  .github/workflows/canary-sites-split.yml
Labels: decoupled-kit, ci/cd

#135 Update build tools docs
  web/docs/Backend Starters/Decoupled Drupal/creating-new-project.md
  web/docs/Backend Starters/Decoupled WordPress/creating-new-project.md
  web/docs/Packages/drupal-kit/classes/src_PantheonDrupalState.default.md
  web/docs/Packages/drupal-kit/interfaces/src_types_types.authInit.md
  web/docs/Packages/drupal-kit/modules/src_fetch_defaultFetch.md
  web/docs/Packages/drupal-kit/modules/src_utils_addSurrogateKeyHeader.md
  web/docs/Packages/drupal-kit/modules/src_utils_updateMaxAge.md
  web/docs/Packages/wordpress-kit/classes/src_lib_ApolloClientFactory.default.md
Labels: documentation

#137 DB-2109: Add a canary repo split for `gatsby-wordpress-starter`
  .github/workflows/canary-sites-split.yml
Labels: decoupled-kit, ci/cd

#138 DB-2241: Add canary split for next-drupal with default data
  .github/workflows/canary-sites-split.yml
Labels: decoupled-kit, ci/cd

#139 DB-2935: Menu Data for footer menu cannot be fetched client side
  .changeset/quick-olives-divide.md
  starters/next-drupal-starter/components/footer.js
  starters/next-drupal-starter/components/layout.js
  starters/next-drupal-starter/pages/articles/[...slug].js
  starters/next-drupal-starter/pages/articles/index.js
  starters/next-drupal-starter/pages/examples/auth-api.js
  starters/next-drupal-starter/pages/examples/pagination/[[...page]].js
  starters/next-drupal-starter/pages/index.js
  starters/next-drupal-starter/pages/pages/[...alias].js
  starters/next-drupal-starter/pages/pages/index.js
  starters/next-drupal-starter/pages/recipes/[...slug].js
  starters/next-drupal-starter/pages/recipes/index.js
Labels: next-drupal

#141 DB-2219: Refine next env var docs
  web/docs/Frontend Starters/Next Drupal/setting-environment-variables.md
Labels: documentation

#142 DB-2278: Fix regressions with 'page' paths
  .changeset/dull-experts-provide.md
  starters/next-drupal-starter/lib/getPaths.js
  starters/next-drupal-starter/pages/pages/[...alias].js
  starters/next-drupal-starter/pages/pages/index.js
Labels: next-drupal, bugfix

#143 Sprint 25 Release 1 - canary -> main
  .changeset/dull-experts-provide.md
  .changeset/funny-toes-draw.md
  .changeset/mighty-pianos-bow.md
  .changeset/quick-olives-divide.md
  .changeset/strange-walls-design.md
  .github/workflows/canary-sites-split.yml
  starters/next-drupal-starter/components/footer.js
  starters/next-drupal-starter/components/grid.js
  starters/next-drupal-starter/components/layout.js
  starters/next-drupal-starter/components/paginator.js
  starters/next-drupal-starter/lib/getPaths.js
  starters/next-drupal-starter/lib/isMultiLanguage.js
  starters/next-drupal-starter/pages/articles/[...slug].js
  starters/next-drupal-starter/pages/articles/index.js
  starters/next-drupal-starter/pages/examples/auth-api.js
  starters/next-drupal-starter/pages/examples/pagination/[[...page]].js
  starters/next-drupal-starter/pages/index.js
  starters/next-drupal-starter/pages/pages/[...alias].js
  starters/next-drupal-starter/pages/pages/index.js
  starters/next-drupal-starter/pages/recipes/[...slug].js
  starters/next-drupal-starter/pages/recipes/index.js
  web/docs/Backend Starters/Decoupled Drupal/creating-new-project.md
  web/docs/Backend Starters/Decoupled WordPress/creating-new-project.md
  web/docs/Frontend Starters/Next Drupal/implementing-preview.md
  web/docs/Frontend Starters/Next Drupal/setting-environment-variables.md
  web/docs/Packages/drupal-kit/classes/src_PantheonDrupalState.default.md
  web/docs/Packages/drupal-kit/interfaces/src_types_types.authInit.md
  web/docs/Packages/drupal-kit/modules/src_fetch_defaultFetch.md
  web/docs/Packages/drupal-kit/modules/src_utils_addSurrogateKeyHeader.md
  web/docs/Packages/drupal-kit/modules/src_utils_updateMaxAge.md
  web/docs/Packages/wordpress-kit/classes/src_lib_ApolloClientFactory.default.md
Labels: release

#146 DB-3090: Initialize `next-wordpress-starter`
  .changeset/sweet-carrots-listen.md
  .eslintrc
  pnpm-lock.yaml
  starters/next-wordpress-starter/.env.example
  starters/next-wordpress-starter/.eslintrc.json
  starters/next-wordpress-starter/.gitignore
  starters/next-wordpress-starter/LICENSE.md
  starters/next-wordpress-starter/README.md
  starters/next-wordpress-starter/next.config.js
  starters/next-wordpress-starter/package.json
  starters/next-wordpress-starter/pages/_app.js
  starters/next-wordpress-starter/pages/api/hello.js
  starters/next-wordpress-starter/pages/index.js
  starters/next-wordpress-starter/postcss.config.js
  starters/next-wordpress-starter/public/favicon.ico
  starters/next-wordpress-starter/public/pantheon.png
  starters/next-wordpress-starter/styles/globals.css
  starters/next-wordpress-starter/tailwind.config.js
Labels: next-wordpress-starter

#148 Clean up peer dependency warnings and latest audit
  package.json
  packages/drupal-kit/package.json
  packages/drupal-kit/rollup.config.js
  packages/wordpress-kit/package.json
  packages/wordpress-kit/rollup.config.js
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/package.json
  starters/gatsby-wordpress-starter/tailwind.config.js
  web/package.json
Labels: security, dependencies

#150 DB-3206: Update DrupalState
  .changeset/light-peaches-fold.md
  .changeset/sour-buttons-grab.md
  packages/drupal-kit/package.json
  pnpm-lock.yaml
  starters/next-drupal-starter/lib/getPaths.js
  starters/next-drupal-starter/lib/getPreview.js
  starters/next-drupal-starter/package-lock.json
  starters/next-drupal-starter/pages/404.js
  starters/next-drupal-starter/pages/api/clear-preview.js
  starters/next-drupal-starter/pages/api/preview.js
  starters/next-drupal-starter/pages/articles/[...slug].js
  starters/next-drupal-starter/pages/articles/index.js
  starters/next-drupal-starter/pages/examples/auth-api.js
  starters/next-drupal-starter/pages/index.js
  starters/next-drupal-starter/pages/pages/[...alias].js
  starters/next-drupal-starter/pages/pages/index.js
  starters/next-drupal-starter/pages/recipes/[...slug].js
  starters/next-drupal-starter/pages/recipes/index.js
Labels: next-drupal, drupal-kit

#153 Sprint 26 Release 1 - canary -> main
  .changeset/config.json
  .changeset/light-peaches-fold.md
  .changeset/seven-crabs-cry.md
  .changeset/sour-buttons-grab.md
  .changeset/sweet-carrots-listen.md
  .eslintrc
  .github/scripts/update-lockfiles.sh
  README.md
  package.json
  packages/drupal-kit/package.json
  packages/drupal-kit/rollup.config.js
  packages/wordpress-kit/package.json
  packages/wordpress-kit/rollup.config.js
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/package.json
  starters/gatsby-wordpress-starter/tailwind.config.js
  starters/next-drupal-starter/lib/getPaths.js
  starters/next-drupal-starter/lib/getPreview.js
  starters/next-drupal-starter/package-lock.json
  starters/next-drupal-starter/pages/404.js
  starters/next-drupal-starter/pages/api/clear-preview.js
  starters/next-drupal-starter/pages/api/preview.js
  starters/next-drupal-starter/pages/articles/[...slug].js
  starters/next-drupal-starter/pages/articles/index.js
  starters/next-drupal-starter/pages/examples/auth-api.js
  starters/next-drupal-starter/pages/index.js
  starters/next-drupal-starter/pages/pages/[...alias].js
  starters/next-drupal-starter/pages/pages/index.js
  starters/next-drupal-starter/pages/recipes/[...slug].js
  starters/next-drupal-starter/pages/recipes/index.js
  starters/next-wordpress-starter/.env.example
  starters/next-wordpress-starter/.eslintrc.json
  starters/next-wordpress-starter/.gitignore
  starters/next-wordpress-starter/LICENSE.md
  starters/next-wordpress-starter/README.md
  starters/next-wordpress-starter/components/footer.js
  starters/next-wordpress-starter/components/header.js
  starters/next-wordpress-starter/components/layout.js
  starters/next-wordpress-starter/components/page-header.js
  starters/next-wordpress-starter/next.config.js
  starters/next-wordpress-starter/package.json
  starters/next-wordpress-starter/pages/_app.js
  starters/next-wordpress-starter/pages/api/hello.js
  starters/next-wordpress-starter/pages/index.js
  starters/next-wordpress-starter/pages/pages/index.js
  starters/next-wordpress-starter/pages/posts/index.js
  starters/next-wordpress-starter/postcss.config.js
  starters/next-wordpress-starter/public/favicon.ico
  starters/next-wordpress-starter/public/pantheon.png
  starters/next-wordpress-starter/styles/globals.css
  starters/next-wordpress-starter/tailwind.config.js
  web/package.json
Labels: release

#154 Update versions
  .changeset/light-peaches-fold.md
  .changeset/seven-crabs-cry.md
  .changeset/sour-buttons-grab.md
  .changeset/sweet-carrots-listen.md
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  starters/gatsby-wordpress-starter/package-lock.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package-lock.json
  starters/next-wordpress-starter/package.json
Labels: release
