Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-09, with the labels that each got.

#856 DB-6705: Fix Drupal decoupled-router validation
  .changeset/grumpy-boxes-unite.md
  .changeset/mighty-keys-repeat.md
  packages/decoupled-kit-health-check/__mocks__/server/drupal/requestHandlers.ts
  packages/decoupled-kit-health-check/__mocks__/server/wordpress/requestHandlers.ts
  packages/decoupled-kit-health-check/__tests__/NextDrupalHealthCheck.test.ts
  packages/decoupled-kit-health-check/__tests__/__snapshots__/NextDrupalHealthCheck.test.ts.snap
  packages/decoupled-kit-health-check/package.json
  packages/decoupled-kit-health-check/src/classes/NextDrupalHealthCheck.ts
  pnpm-lock.yaml
Labels: next-drupal, health-check

#857 DB-6728: Fix next-wp trailing slash in WPGRAPHQL_URL breaks IMAGE_DOMAIN
  .changeset/tall-garlics-suffer.md
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/next.config.js
Labels: next-wordpress, cli-templates

#858 DB-6459: Add engines field to package.jsons + some cleanup
  .changeset/tasty-students-end.md
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/sharedPkgJsonFields.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/sharedPkgJsonFields.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/tailwindcssDeps.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/tailwindcssDeps.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/readme-shared/index.ts
  packages/create-pantheon-decoupled-kit/src/types.ts
Labels: next-drupal, gatsby-wordpress, next-wordpress, cli-templates

#859 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#861 DB-4833: specify platform docs
  pnpm-lock.yaml
  web/docs/Backend Starters/Decoupled Drupal/creating-new-project.mdx
  web/docs/Backend Starters/Decoupled WordPress/creating-new-project.md
  web/docs/Backend Starters/terminus-decoupled-kit-plugin.md
  web/docs/decoupled-kit-overview.mdx
  web/docs/pantheon-front-end-sites.md
  web/docusaurus.config.js
  web/package.json
  web/src/css/custom.css
  web/src/theme/Admonition/index.js
  web/src/theme/Admonition/styles.module.css
Labels: documentation

#860 Make all PackageVersionData keys optional only on BaseGeneratorData
  packages/create-pantheon-decoupled-kit/src/types.ts
Labels: bugfix, cli

#862 Exit prerelease mode for sprint 18
  .changeset/pre.json
Labels: release

#864 Sprint 18 Release - canary -> main
  .changeset/grumpy-boxes-unite.md
  .changeset/mighty-keys-repeat.md
  .changeset/pre.json
  .changeset/tall-garlics-suffer.md
  .changeset/tasty-students-end.md
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/next.config.js
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/sharedPkgJsonFields.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/sharedPkgJsonFields.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/tailwindcssDeps.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/tailwindcssDeps.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/readme-shared/index.ts
  packages/create-pantheon-decoupled-kit/src/types.ts
  packages/decoupled-kit-health-check/CHANGELOG.md
  packages/decoupled-kit-health-check/__mocks__/server/drupal/requestHandlers.ts
  packages/decoupled-kit-health-check/__mocks__/server/wordpress/requestHandlers.ts
  packages/decoupled-kit-health-check/__tests__/NextDrupalHealthCheck.test.ts
  packages/decoupled-kit-health-check/__tests__/__snapshots__/NextDrupalHealthCheck.test.ts.snap
  packages/decoupled-kit-health-check/package.json
  packages/decoupled-kit-health-check/src/classes/NextDrupalHealthCheck.ts
  pnpm-lock.yaml
  web/docs/Backend Starters/Decoupled Drupal/creating-new-project.mdx
  web/docs/Backend Starters/Decoupled WordPress/creating-new-project.md
  web/docs/Backend Starters/terminus-decoupled-kit-plugin.md
  web/docs/decoupled-kit-overview.mdx
  web/docs/pantheon-front-end-sites.md
  web/docusaurus.config.js
  web/package.json
  web/src/css/custom.css
  web/src/theme/Admonition/index.js
  web/src/theme/Admonition/styles.module.css
Labels: release

#866 Sprint 18 Backmerge Main -> Canary
  .changeset/grumpy-boxes-unite.md
  .changeset/mighty-keys-repeat.md
  .changeset/pre.json
  .changeset/tall-garlics-suffer.md
  .changeset/tasty-students-end.md
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/decoupled-kit-health-check/CHANGELOG.md
  packages/decoupled-kit-health-check/package.json
Labels: release

#867 Enter pre-release for sprint 19
  .changeset/pre.json
Labels: release

#869 DB-6721: Use published eslint-config for docs site
  package.json
  pnpm-lock.yaml
  web/.eslintrc
  web/package.json
Labels: documentation, bugfix

#870 DB-6765: Opt out health check with an env var
  .changeset/good-fans-invent.md
  .changeset/yellow-gorillas-jump.md
  packages/decoupled-kit-health-check/README.md
  packages/decoupled-kit-health-check/__tests__/__snapshots__/GatsbyWordPressHealthCheck.test.ts.snap
  packages/decoupled-kit-health-check/__tests__/__snapshots__/NextDrupalHealthCheck.test.ts.snap
  packages/decoupled-kit-health-check/__tests__/__snapshots__/NextWordPressHealthCheck.test.ts.snap
  packages/decoupled-kit-health-check/__tests__/noDKHC.test.ts
  packages/decoupled-kit-health-check/src/bin.ts
  packages/decoupled-kit-health-check/src/classes/NextDrupalHealthCheck.ts
  packages/decoupled-kit-health-check/src/classes/NextWordPressHealthCheck.ts
  packages/decoupled-kit-health-check/src/classes/errors.ts
  packages/decoupled-kit-health-check/src/utils/logger.ts
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/troubleshooting.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/troubleshooting.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/troubleshooting.md
Labels: documentation, cli-templates, health-check

#873 Add a redirect to the previous front page to current
  web/src/pages/docs/decoupled-kit-overview.jsx
Labels: documentation

#872 DB-6775: Use Pantheon-SKey to obtain surrogate key header
  .changeset/bright-bottles-end.md
  .changeset/nasty-spoons-attack.md
  packages/drupal-kit/src/lib/defaultFetch.ts
  packages/wordpress-kit/__mocks__/server/basicPostsQuery.ts
  packages/wordpress-kit/src/lib/GraphQLClientFactory.ts
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
Labels: drupal-kit, wordpress-kit, cli-templates

#877 DB-5856: [docs] Audit uses of back-end and front-end for consistency
  web/docs/Backend Starters/Decoupled Drupal/add-ons.md
  web/docs/Backend Starters/Decoupled Drupal/caching-considerations.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-build-hooks.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-existing-project.md
  web/docs/Backend Starters/Decoupled Drupal/creating-a-new-project.mdx
  web/docs/Backend Starters/Decoupled Drupal/local-development.md
  web/docs/Backend Starters/Decoupled WordPress/caching-considerations.md
  web/docs/Backend Starters/Decoupled WordPress/configuring-existing-project.md
  web/docs/Backend Starters/Decoupled WordPress/local-development.md
  web/docs/Backend Starters/terminus-decoupled-kit-plugin.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
  web/docs/decoupled-kit-overview.mdx
Labels: documentation

#876 DB-6772: FES Settings Docs Updates
  web/docs/Backend Starters/Decoupled WordPress/configuring-preview-site.md
  web/docs/Backend Starters/Decoupled WordPress/creating-a-new-project.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/implementing-preview.md
Labels: documentation

#879 Exit pre-release mode for sprint 19
  .changeset/pre.json
Labels: release

#884 Enter pre-release for sprint 20
  .changeset/pre.json
Labels: release

#878 DB-6521 Update dependencies
  .changeset/angry-poets-smell.md
  .changeset/cuddly-beds-worry.md
  .changeset/fifty-squids-listen.md
  .changeset/green-laws-battle.md
  .changeset/hot-windows-decide.md
  .changeset/loud-fireants-begin.md
  .changeset/many-lies-retire.md
  .changeset/odd-countries-carry.md
  .changeset/yellow-guests-remember.md
  .circleci/config.yml
  README.md
  package.json
  packages/cms-kit/package.json
  packages/configs/eslint/package.json
  packages/configs/other/package.json
  packages/create-pantheon-decoupled-kit/__mocks__/inquirer.ts
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/__tests__/setupFile.js
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/tailwindcssDeps.ts
  packages/decoupled-kit-health-check/package.json
  packages/drupal-kit/package.json
  packages/nextjs-kit/package.json
  packages/wordpress-kit/package.json
  pnpm-lock.yaml
  web/docs/contributing.md
  web/docusaurus.config.js
  web/package.json
Labels: decoupled-kit, dependencies

#885 Use pnpm 8.8.0 for all workflows
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd, bugfix
