Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-10, with the labels that each got.

#887 Nightly Audit on 10/05/23
  package.json
  pnpm-lock.yaml
Labels: security, dependencies

#901 KIT-15: Init cli add-on regression test workflows
  .github/actions/setup-playwright/action.yml
  .github/workflows/cli-addon-tests.yml
  .gitignore
  ci-tests/package.json
  ci-tests/tests/gatsby-wp-acf.spec.ts
  ci-tests/tests/gatsby-wp-acf.spec.ts-snapshots/Gatsby-WP-ACF-Add-on-The-homepage-snapshot-has-no-regressions-1-linux.png
  ci-tests/tests/next-drupal-search.spec.ts
  ci-tests/tests/next-drupal-search.spec.ts-snapshots/Drupal-Search-Addon-The-homepage-snapshot-has-no-regressions-1-linux.png
  ci-tests/tests/next-wp-acf.spec.ts
  ci-tests/tests/next-wp-acf.spec.ts-snapshots/Next-WP-ACF-Add-on-The-homepage-snapshot-has-no-regressions-1-linux.png
  configs/prettier.config.js
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: ci/cd, cli

#902 KIT-42: Scaffold react kit
  .changeset/dry-rice-pay.md
  .vscode/extensions.json
  packages/nextjs-kit/package.json
  packages/react-kit/.eslintrc
  packages/react-kit/.gitignore
  packages/react-kit/README.md
  packages/react-kit/__tests__/snapshotTests/__snapshots__/button.test.tsx.snap
  packages/react-kit/__tests__/snapshotTests/button.test.tsx
  packages/react-kit/lint-staged.config.cjs
  packages/react-kit/package.json
  packages/react-kit/postcss.config.js
  packages/react-kit/src/components/Button/index.tsx
  packages/react-kit/src/index.ts
  packages/react-kit/src/style.css
  packages/react-kit/tailwind.config.ts
  packages/react-kit/tsconfig.build.json
  packages/react-kit/tsconfig.json
  packages/react-kit/tsup.config.ts
  packages/react-kit/vite.config.ts
  pnpm-lock.yaml
  tsconfig.json
  web/generateTypedocOptions.js
Labels: documentation, nextjs-kit, react-kit

#910 KIT-46: `react kit` storybook
  .github/workflows/canary-sites-split.yml
  package.json
  packages/react-kit/.eslintrc
  packages/react-kit/.gitignore
  packages/react-kit/.storybook/main.ts
  packages/react-kit/.storybook/preview.ts
  packages/react-kit/__tests__/snapshotTests/button.test.tsx
  packages/react-kit/package.json
  packages/react-kit/src/components/Button/index.tsx
  packages/react-kit/src/index.css
  packages/react-kit/src/index.ts
  packages/react-kit/src/stories/Button.stories.tsx
  packages/react-kit/tsconfig.json
  packages/react-kit/tsup.config.ts
  packages/react-kit/vite.config.ts
  pnpm-lock.yaml
Labels: ci/cd, react-kit

#911 Fix typo
  .github/workflows/canary-sites-split.yml
Labels: ci/cd, bugfix

#912 KIT-46: Fix react-kit storybook deployment
  .github/templates/emtpy-package.json
  .github/workflows/canary-sites-split.yml
Labels: ci/cd, bugfix

#913 KIT-46: Setup pnpm if building storybook
  .github/actions/setup-node/action.yml
  .github/workflows/canary-sites-split.yml
Labels: ci/cd, bugfix

#914 KIT-46: Use string instead of fake boolean
  .github/actions/setup-node/action.yml
  .github/workflows/canary-sites-split.yml
Labels: ci/cd, bugfix

#915 KIT-46: Fix filename typo
  .github/templates/empty-package.json
Labels: ci/cd, bugfix

#916 KIT-46: Fix typo
  .github/workflows/canary-sites-split.yml
Labels: ci/cd, bugfix
