Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-06, with the labels that each got.

#724 DB-6288: `getDrupalSearchResults` uses `example_index`
  .changeset/stupid-terms-travel.md
  packages/drupal-kit/__mocks__/server/getDrupalSearchResultsResponseHandlers.ts
  packages/drupal-kit/__tests__/getDrupalSearchResults.test.ts
  packages/drupal-kit/src/lib/getDrupalSearchResults.ts
Labels: drupal-kit

#725 DB-6289: Fix Broken Search Links
  .changeset/pretty-waves-float.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/pages/search/[[...searchAlias]].jsx
Labels: next-drupal, cli

#722 DB-6177: [next-drupal] App Directory Scaffolding
  .changeset/perfect-rings-wink.md
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal.generator.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/.env.development.local.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/.env.example
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/.eslintrc.json
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/.lando.yml
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/.nvmrc
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/.prettierignore
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/.prettierrc
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/LICENSE.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/app/favicon.ico
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/app/globals.css
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/app/layout.tsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/app/page.module.css
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/app/page.tsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/gitignore
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/next.config.js
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/public/collapse.svg
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/public/next.svg
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/public/pantheon.png
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/public/vercel.svg
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/scripts/get-locales.js
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/tsconfig.json
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-app/vite.config.js
  scripts/generate-starters.ts
Labels: next-drupal, cli

#727 Exit pre-release for sprint 11
  .changeset/pre.json
Labels: release

#729 Sprint 11: canary -> main
  .changeset/pre.json
  .changeset/pretty-waves-float.md
  .changeset/soft-tools-rescue.md
  .changeset/stupid-terms-travel.md
  package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/pages/search/[[...searchAlias]].jsx
  packages/create-pantheon-decoupled-kit/src/types.ts
  packages/create-pantheon-decoupled-kit/src/utils/helpMenu.ts
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/__mocks__/server/getDrupalSearchResultsResponseHandlers.ts
  packages/drupal-kit/__tests__/getDrupalSearchResults.test.ts
  packages/drupal-kit/package.json
  packages/drupal-kit/src/lib/getDrupalSearchResults.ts
  pnpm-lock.yaml
  web/docs/Backend Starters/Decoupled Drupal/creating-new-project.md
Labels: release

#732 Enter prerelease mode for sprint 12
  .changeset/pre.json
Labels: release

#734 Exit pre-release to release docs
  .changeset/pre.json
Labels: documentation, release

#735 Docs Release
  .changeset/pre.json
  web/docs/Packages/cms-kit/modules.md
  web/docs/Packages/create-pantheon-decoupled-kit/index.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DecoupledKitGenerator.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DefaultAnswers.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/TemplateData.md
  web/docs/Packages/create-pantheon-decoupled-kit/modules.md
  web/docs/Packages/drupal-kit/classes/DrupalState.md
  web/docs/Packages/drupal-kit/interfaces/_category_.yml
  web/docs/Packages/drupal-kit/interfaces/authInit.md
  web/docs/Packages/drupal-kit/modules.md
  web/docs/Packages/nextjs-kit/interfaces/ContentProps.md
  web/docs/Packages/nextjs-kit/interfaces/FooterMenuProps.md
  web/docs/Packages/nextjs-kit/interfaces/HeaderProps.md
  web/docs/Packages/nextjs-kit/interfaces/LinkProps.md
  web/docs/Packages/nextjs-kit/interfaces/PaginationProps.md
  web/docs/Packages/nextjs-kit/interfaces/PreviewRibbonProps.md
  web/docs/Packages/nextjs-kit/interfaces/RecipeProps.md
  web/docs/Packages/nextjs-kit/interfaces/SortOptions.md
  web/docs/Packages/nextjs-kit/modules.md
  web/docs/Packages/wordpress-kit/classes/GraphqlClientFactory.md
  web/docs/Packages/wordpress-kit/index.md
  web/docs/Packages/wordpress-kit/modules.md
Labels: documentation, release

#741 DB-4189: add DrupalState code sample to surrogate key docs page
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
Labels: documentation

#742 DB-4188: add wordpress-kit code sample to surrogate key docs page
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
Labels: documentation

#745 Fix subpath exports for nextjs-kit
  .changeset/dirty-garlics-switch.md
  packages/nextjs-kit/package.json
  packages/nextjs-kit/tsup.config.ts
Labels: nextjs-kit

#746 Update `feat/app-directory-generators` to `feat/typescript-generators`
  .changeset/dirty-garlics-switch.md
  .changeset/pre.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/nextjs-kit/tsup.config.ts
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
Labels: decoupled-kit

#750 Exit pre-release mode for sprint 12
  .changeset/pre.json
Labels: release

#751 Sprint 12 Release: Canary -> Main
  .changeset/dirty-garlics-switch.md
  .changeset/pre.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/nextjs-kit/tsup.config.ts
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
Labels: release

#754 Sprint 12 - backmerge main -> canary
  .changeset/dirty-garlics-switch.md
  .changeset/pre.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
Labels: release

#755 Enter pre-release mode for sprint 13
  .changeset/pre.json
Labels: release

#757 Nightly Audit on 06/23/23
  package.json
  pnpm-lock.yaml
Labels: security, dependencies

#749 DB-6357: Upgrade gatsby-wp templates to gastby v5
  .changeset/gorgeous-terms-pay.md
  packages/create-pantheon-decoupled-kit/__tests__/convertCSSModules.test.ts
  packages/create-pantheon-decoupled-kit/lint-staged.config.cjs
  packages/create-pantheon-decoupled-kit/src/actions/convertCSSModules.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/gatsby-config.ts.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/createPagesUtils/getPages.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/createPagesUtils/getPosts.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/types.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/footer.module.css
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/footer.module.css.d.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/footer.tsx
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/paginator.module.css
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/post.module.css.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/post.tsx
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/authApi.module.css
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/authApi.module.css.d.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/authApi.tsx
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/examples.module.css
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/examples.module.css.d.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/examples.tsx
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/pagination.module.css
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/vite.config.js
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/tailwindcssDepsT.ts
Labels: gatsby-wordpress, cli-templates

#758 Add changeset to bump nextjs-kit version in the CLI
  .changeset/rotten-hotels-provide.md
Labels: cli

#759 DB-5578: Refactor gatsby-wp-acf-addon to TypeScript
  .changeset/spicy-seals-arrive.md
  packages/create-pantheon-decoupled-kit/lint-staged.config.cjs
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/lib/createPagesUtils/getPosts.ts.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/gatsby-types.d.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/post.jsx
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/post.module.css.hbs
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/postTemplate.module.css.d.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/postTemplate.module.css.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/postTemplate.tsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/createPagesUtils/getPages.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/createPagesUtils/getPosts.ts.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/grid.tsx
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/index.tsx
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/pagesIndex.tsx
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/postTemplate.tsx
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/postTemplate.tsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/postsIndex.tsx
  packages/create-pantheon-decoupled-kit/src/templates/partials/gatsby-wp/postTemplate.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/gatsby-wp/wpPostsQuery.ts
Labels: gatsby-wordpress, cli-addon, cli-templates

#760 Fix gatsby wp `getPosts` template
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/createPagesUtils/getPosts.ts.ts
Labels: gatsby-wordpress, bugfix, cli-templates

#761 DB-6330: (chore) bump `@gdwc/drupal-state`
  .changeset/healthy-numbers-judge.md
  .changeset/lucky-socks-attend.md
  package.json
  packages/drupal-kit/package.json
  packages/drupal-kit/src/lib/PantheonDrupalState.ts
  packages/nextjs-kit/package.json
  pnpm-lock.yaml
  scripts/check-built.ts
  scripts/post-install
Labels: dependencies, drupal-kit, nextjs-kit

#763 Next config change no longer necessary for Drupal surrogate key example
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
Labels: documentation
