Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-01, with the labels that each got.

#463 Update footer in snapshots for 2023
  packages/nextjs-kit/src/__tests__/snapshotTests/__snapshots__/footer.test.tsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/authApi.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/homepage.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/page.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagesIndex.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagination.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/post.test.jsx.snap
  starters/gatsby-wordpress-starter/__tests__/snapshotTests/__snapshots__/postsIndex.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/articles.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/auth-api.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/examples-index.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/homepage.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/pages.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/pagination.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/recipes.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/default/ssr-isr-example.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/[...alias].test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/articles.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/auth-api.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/examples-index.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/homepage.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/pages.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/pagination.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/recipes.test.jsx.snap
  starters/next-drupal-starter/__tests__/__snapshots__/umami/ssr-isr-example.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/auth-api.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/example-index.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/homepage.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pages.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/pagination.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/posts.test.jsx.snap
  starters/next-wordpress-starter/__tests__/snapshotTests/__snapshots__/ssg-isr-example.test.jsx.snap
Labels: next-drupal, gatsby-wordpress, next-wordpress, nextjs-kit

#469 DB-5194: React 18 Gatsby Update
  .changeset/afraid-needles-fold.md
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/package.json
Labels: gatsby-wordpress

#471 DB-5231: Support GraphQL over HTTP GET
  .changeset/eighty-timers-fold.md
  packages/wordpress-kit/__tests__/GraphqlClientFactory.test.ts
  packages/wordpress-kit/src/lib/graphqlClient/GraphqlClientFactory.ts
Labels: wordpress-kit

#470 Canary Release (canary)
  .changeset/pre.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: 🐥 canary release

#476 Sprint 2 - backmerge main -> canary
  .changeset/afraid-needles-fold.md
  .changeset/eighty-timers-fold.md
  .changeset/great-bulldogs-bathe.md
  .changeset/little-fans-call.md
  .changeset/pre.json
  .changeset/spotty-seahorses-hang.md
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#477 Enter pre-release mode for sprint 2
  .changeset/pre.json
Labels: release

#478 DB-2799: Documentation for Configuring Drupal Preview site.
  web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/implementing-preview.md
Labels: documentation

#482 DB-4626: Update monorepo `.nvmrc` files
  .changeset/hip-ladybugs-care.md
  .changeset/tidy-ligers-crash.md
  .nvmrc
  starters/gatsby-wordpress-starter/.nvmrc
  starters/next-wordpress-starter/.nvmrc
  web/.nvmrc
Labels: documentation, gatsby-wordpress, decoupled-kit, next-wordpress

#480 DB-3372: Initialize `create-pantheon-decoupled-kit`
  .changeset/config.json
  .changeset/kind-chairs-camp.md
  .prettierignore
  configs/eslint/index.js
  package.json
  packages/create-pantheon-decoupled-kit/.eslintrc
  packages/create-pantheon-decoupled-kit/.gitignore
  packages/create-pantheon-decoupled-kit/LICENSE.md
  packages/create-pantheon-decoupled-kit/README.md
  packages/create-pantheon-decoupled-kit/__mocks__/node-plop.ts
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/generators/index.ts
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/generators/test-append.generator.ts
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/generators/test.generator.ts
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/templates/simple/test-template.js.hbs
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/templates/test/test-template.js.hbs
  packages/create-pantheon-decoupled-kit/esbuild.js
  packages/create-pantheon-decoupled-kit/lint-staged.config.cjs
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/scripts/copyTemplates.ts
  packages/create-pantheon-decoupled-kit/scripts/watchTemplates.ts
  packages/create-pantheon-decoupled-kit/src/bin.ts
  packages/create-pantheon-decoupled-kit/src/generators/index.ts
  packages/create-pantheon-decoupled-kit/src/generators/test-append.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/test.generator.ts
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/simple/test-template.js.hbs
  packages/create-pantheon-decoupled-kit/src/templates/test/test-template.js.hbs
  packages/create-pantheon-decoupled-kit/src/types.ts
  packages/create-pantheon-decoupled-kit/tsconfig.json
  packages/create-pantheon-decoupled-kit/vite.config.js
  packages/create-pantheon-decoupled-kit/watch.example.ts
  pnpm-lock.yaml
  tsconfig.json
  web/docs/Packages/create-pantheon-decoupled-kit/_category_.yml
  web/docs/Packages/create-pantheon-decoupled-kit/index.md
  web/docs/Packages/create-pantheon-decoupled-kit/modules.md
  web/docusaurus.config.js
  web/generateTypedocOptions.js
Labels: cli

#483 DB-4628: CIrcle CI and Git Hub Actions Node Upgrade
  .circleci/config.yml
  .github/workflows/canary-release.yml
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
  README.md
Labels: ci/cd

#487 Upgrade dependencies
  .changeset/cool-wasps-burn.md
  configs/eslint/package.json
  package.json
  packages/cms-kit/package.json
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/package.json
  packages/nextjs-kit/package.json
  packages/wordpress-kit/package.json
  pnpm-lock.yaml
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/package.json
  web/package.json
Labels: security, dependencies

#485 DB-1052: Configuring Build Hooks Documentation
  web/docs/Backend Starters/Decoupled WordPress/configuring-build-hooks.md
Labels: documentation

#491 Fix missing dependency
  .changeset/happy-moose-try.md
  packages/create-pantheon-decoupled-kit/package.json
  pnpm-lock.yaml
Labels: bugfix

#492 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#493 Exit pre-release for sprint 2
  .changeset/pre.json
Labels: release
