Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-08, with the labels that each got.

#813 DB-6588: [gatsby-wp] pagination fails gracefully
  .changeset/itchy-shrimps-check.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/gatsby-node.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/createPagesUtils/createPaginationExamplePage.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/lib/paginationPostsQuery.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/pagination.module.css
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/pagination.module.css.d.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/templates/paginationExample.tsx
Labels: gatsby-wordpress, cli-templates

#815 Exit pre-release for sprint 15
  .changeset/pre.json
Labels: release

#820 Enter pre-release mode for sprint 16
  .changeset/pre.json
Labels: release

#822 DB-5857: [docs] Add 'Configuring a Preview Site' entry under WP BE Section
  web/docs/Backend Starters/Decoupled WordPress/add-ons.md
  web/docs/Backend Starters/Decoupled WordPress/configuring-build-hooks.md
  web/docs/Backend Starters/Decoupled WordPress/configuring-preview-site.md
Labels: documentation

#821 Update troubleshooting in docs and readme re: dkhc
  .changeset/eleven-coins-dance.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/troubleshooting.md
Labels: documentation, gatsby-wordpress, cli-templates

#823 DB-6634: `BACKEND_URL` not required for search
  .changeset/tiny-kangaroos-yawn.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/pages/search/[[...searchAlias]].jsx
Labels: bugfix, cli, cli-templates

#824 DB-5859: Refactor branding and navigation
  pnpm-lock.yaml
  web/README.md
  web/docs/Backend Starters/Decoupled Drupal/index.mdx
  web/docs/Backend Starters/Decoupled WordPress/index.mdx
  web/docs/Backend Starters/index.mdx
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/index.mdx
  web/docs/Frontend Starters/Gatsby/index.mdx
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/index.mdx
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/index.mdx
  web/docs/Frontend Starters/Next.js/index.mdx
  web/docs/Frontend Starters/index.mdx
  web/docs/Packages/index.mdx
  web/docs/decoupled-kit-overview.md
  web/docs/decoupled-kit-overview.mdx
  web/docusaurus.config.js
  web/package.json
  web/src/components/DocCardList_Custom/index.js
  web/src/components/DocCard_Custom/index.js
  web/src/components/DocCard_Custom/styles.module.css
  web/src/components/HomepageFeatures/index.js
  web/src/components/HomepageFeatures/styles.module.css
  web/src/components/OverviewCardList/index.js
  web/src/pages/index.js
  web/src/pages/index.jsx
  web/src/pages/index.module.css
  web/src/pages/markdown-page.md
Labels: documentation, enhancement

#825 DB-6520: Add links and entry for Panthon Front-End Sites
  .vscode/extensions.json
  web/docs/Backend Starters/_category_.json
  web/docs/Packages/_category_.json
  web/docs/contributing.md
  web/docs/decoupled-kit-overview.mdx
  web/docs/pantheon-front-end-sites.md
  web/docusaurus.config.js
  web/src/components/OverviewCardList/index.js
Labels: documentation

#828 DB-6644: Fix trailing slash fails health check for WP based starters
  .changeset/five-news-train.md
  .changeset/nice-candles-unite.md
  packages/decoupled-kit-health-check/__tests__/GatsbyWordPressHealthCheck.test.ts
  packages/decoupled-kit-health-check/__tests__/NextWordPressHealthCheck.test.ts
  packages/decoupled-kit-health-check/src/classes/GatsbyWordPressHealthCheck.ts
  packages/decoupled-kit-health-check/src/classes/NextWordPressHealthCheck.ts
Labels: health-check

#827 DB-6233: Add comments to .env.example env vars
  .changeset/clever-chefs-exist.md
  .changeset/happy-eggs-rescue.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/.env.example
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/.env.example
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/.env.example
  packages/decoupled-kit-health-check/__tests__/__snapshots__/NextWordPressHealthCheck.test.ts.snap
  packages/decoupled-kit-health-check/src/classes/NextWordPressHealthCheck.ts
Labels: next-drupal, gatsby-wordpress, next-wordpress, cli-templates

#830 DB-5858: Audit Navigation Structure
  web/docs/Backend Starters/Decoupled Drupal/configuring-build-hooks.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-existing-project.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md
  web/docs/Backend Starters/Decoupled Drupal/cors.md
  web/docs/Backend Starters/Decoupled Drupal/local-development.md
  web/docs/Backend Starters/Decoupled Drupal/updating-dependencies.md
  web/docs/Backend Starters/Decoupled WordPress/caching-considerations.md
  web/docs/Backend Starters/Decoupled WordPress/configuring-build-hooks.md
  web/docs/Backend Starters/Decoupled WordPress/configuring-existing-project.md
  web/docs/Backend Starters/Decoupled WordPress/local-development.md
  web/docs/Backend Starters/Decoupled WordPress/managing-dependencies.md
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/add-ons.md
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/troubleshooting.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/add-ons.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/troubleshooting.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/add-ons.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/troubleshooting.md
Labels: documentation

#831 CI: Attempt to fix changeset action
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd

#832 CI: Attempt to fix changeset action #2
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd

#833 CI: Attempt to fix changeset action
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd

#835 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/decoupled-kit-health-check/CHANGELOG.md
  packages/decoupled-kit-health-check/package.json
Labels: 🐥 canary release

#836 CI: Set pull-requests and contents permissions to write
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd

#839 Exit pre-release for belated sprint 16
  .changeset/pre.json
Labels: release

#844 Enter prerelease for sprint 17
  .changeset/pre.json
Labels: release

#845 DB-6235: Update starter kit READMEs
  .changeset/famous-singers-perform.md
  packages/create-pantheon-decoupled-kit/esbuild.js
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/shared/readme/sharedReadme.ts
  packages/create-pantheon-decoupled-kit/src/utils/constants.ts
  packages/create-pantheon-decoupled-kit/src/utils/taggedTemplateHelpers.ts
  web/docs/decoupled-kit-overview.mdx
Labels: next-drupal, gatsby-wordpress, next-wordpress, cli-templates

#847 DB-6235: Use logo based on system theme (dark/light)
  .changeset/brown-countries-prove.md
  packages/create-pantheon-decoupled-kit/src/templates/partials/shared/readme/sharedReadme.ts
Labels: cli-templates

#849 DB-6235: Use correct images for the theme context
  packages/create-pantheon-decoupled-kit/src/templates/partials/shared/readme/sharedReadme.ts
Labels: cli-templates

#848 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#850 Exit prerelease for sprint 17
  .changeset/pre.json
Labels: release

#852 Sprint 17 Release: Canary -> Main
  .changeset/brown-countries-prove.md
  .changeset/famous-singers-perform.md
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/esbuild.js
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/shared/readme/sharedReadme.ts
  packages/create-pantheon-decoupled-kit/src/utils/constants.ts
  packages/create-pantheon-decoupled-kit/src/utils/taggedTemplateHelpers.ts
  web/docs/decoupled-kit-overview.mdx
Labels: release

#854 Sprint 17: backmerge main -> canary
  .changeset/brown-countries-prove.md
  .changeset/famous-singers-perform.md
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: release

#855 Enter pre-release for sprint 18
  .changeset/pre.json
Labels: release
