Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-11, with the labels that each got.

#934 KIT-97: Upgrade to NextJs `v13.5.6`
  .changeset/eight-lamps-yawn.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/package.json.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.ts
  packages/nextjs-kit/package.json
  packages/nextjs-kit/src/components/contentWithImage.tsx
  packages/nextjs-kit/src/components/recipe.tsx
  pnpm-lock.yaml
Labels: security, dependencies, nextjs-kit, cli

#937 KIT-67: Add slack notification to add-on regression test workflow
  .github/workflows/cli-addon-tests.yml
  README.md
Labels: ci/cd

#941 KIT-67: Fix upload path
  .github/workflows/cli-addon-tests.yml
Labels: ci/cd, bugfix

#950 KIT-126: Setup snapshot releases for `feat/*`
  .github/workflows/snapshot-release.yml
  configs/prettier.config.js
Labels: ci/cd

#951 KIT-126: Fix env var name
  .github/workflows/snapshot-release.yml
Labels: ci/cd, bugfix

#953 KIT-126: Use team name instead of slug
  .github/workflows/snapshot-release.yml
Labels: ci/cd, bugfix

#954 KIT-111: Prevent Caching In Test Preview Route
  .changeset/tender-geckos-smash.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/api/preview.js
Labels: next-drupal, cli-templates

#957 KIT-126: Fix tag
  .github/workflows/snapshot-release.yml
Labels: ci/cd, bugfix

#960 KIT-126: Build after version to get proper deps versions in CLI
  .github/workflows/snapshot-release.yml
Labels: ci/cd, bugfix

#955 KIT-72: Implement new header component in the `next-wordpress` starter
  .changeset/fast-cameras-act.md
  .changeset/hungry-tools-invent.md
  .changeset/proud-candles-hug.md
  .changeset/rare-donkeys-compete.md
  configs/prettier.config.js
  package.json
  packages/create-pantheon-decoupled-kit/esbuild.js
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/pages/pages/[...uri].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/pages/pages/[...uri].jsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/pages/posts/[...slug].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/pages/posts/[...slug].jsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/components/layout.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/lib/Menus.js
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/examples/auth-api.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/examples/index.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/examples/pagination/[[...page]].jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/examples/ssg-isr.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/index.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/pages/[...uri].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/pages/[...uri].jsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/pages/index.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/posts/[...slug].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/posts/[...slug].jsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/posts/index.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/public/pantheon-fist-blk.svg
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/styles/globals.css.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/gatsby-wp/postTemplate.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-wp/pageView.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-wp/postView.ts
  packages/create-pantheon-decoupled-kit/tsconfig.json
  packages/create-pantheon-decoupled-kit/tsconfig.typedoc.json
  packages/nextjs-kit/__tests__/snapshotTests/__snapshots__/header.test.tsx.snap
  packages/nextjs-kit/__tests__/snapshotTests/header.test.tsx
  packages/nextjs-kit/package.json
  packages/nextjs-kit/src/components/Header/index.tsx
  packages/nextjs-kit/src/index.ts
  packages/nextjs-kit/tsconfig.build.json
  packages/nextjs-kit/tsconfig.json
  packages/nextjs-kit/tsup.config.ts
  packages/react-kit/.storybook/preview.ts
  packages/react-kit/__tests__/snapshotTests/Header.test.tsx
  packages/react-kit/__tests__/snapshotTests/__snapshots__/Header.test.tsx.snap
  packages/react-kit/package.json
  packages/react-kit/src/components/Header/Header.stories.tsx
  packages/react-kit/src/components/Header/Header.tsx
  packages/react-kit/src/components/Header/props.ts
  packages/react-kit/src/styles.css
  packages/react-kit/tsconfig.build.json
  packages/react-kit/tsconfig.json
  packages/react-kit/tsup.config.ts
  packages/wordpress-kit/src/lib/setOutgoingHeaders.ts
  pnpm-lock.yaml
  tsconfig.json
Labels: next-wordpress, nextjs-kit, cli-templates, react-kit

#961 KIT-25: Drupal FES Settings Developer Docs
  web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md
  web/docs/Backend Starters/Decoupled Drupal/creating-a-new-project.mdx
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/implementing-preview.md
Labels: documentation

#963 KIT-41: [next-drupal] Implement Header
  .changeset/long-starfishes-end.md
  packages/create-pantheon-decoupled-kit/.eslintrc
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/components/layout.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/components/layout.jsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-umami-addon/pages/[...alias].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-umami-addon/pages/[...alias].jsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-umami-addon/pages/recipes/[...slug].jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-umami-addon/pages/recipes/index.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/components/layout.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/components/layout.jsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/[...alias].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/[...alias].jsx.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/articles/[...slug].jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/articles/index.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/examples/auth-api.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/examples/index.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/examples/pagination/[[...page]].jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/examples/ssg-isr.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/index.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/pages/[...alias].jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/pages/index.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/pages/preview-error/[[...alias]].jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/public/pantheon-fist-blk.svg
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/lib/Menus.js
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-drupal/catchAllView.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-drupal/layout.ts
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-wp/pageView.ts
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/examples/ssg-isr.module.css
  packages/create-pantheon-decoupled-kit/src/utils/taggedTemplateHelpers.ts
Labels: next-drupal, cli-templates

#962 KIT-63: Adjust Gatsby Health Check Environment Variable Valid Protocol
  packages/decoupled-kit-health-check/__tests__/GatsbyWordPressHealthCheck.test.ts
  packages/decoupled-kit-health-check/__tests__/__snapshots__/GatsbyWordPressHealthCheck.test.ts.snap
  packages/decoupled-kit-health-check/src/classes/GatsbyWordPressHealthCheck.ts
Labels: health-check
