Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-04, with the labels that each got.

#605 DB-5830: `nextjs-kit` Vite Config Update
  .changeset/young-brooms-argue.md
  packages/nextjs-kit/vite.config.js
Labels: bugfix, nextjs-kit

#611 Add .npmrc to avoid creating it in CI
  .npmrc
Labels: bugfix

#610 Canary Release (canary)
  .changeset/pre.json
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
Labels: 🐥 canary release

#613 Revert "Canary Release (canary)"
  .changeset/pre.json
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
Labels: bugfix

#612 Move .npmrc write out of actions
  .github/workflows/canary-release.yml
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
  .npmrc
Labels: ci/cd, bugfix

#615 Use empty .npmrc, update NPM_TOKEN in CI workflows
  .github/workflows/canary-sites-split.yml
  .npmrc
Labels: ci/cd, bugfix

#614 Canary Release (canary)
  .changeset/pre.json
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
Labels: 🐥 canary release

#616 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#607 DB-5717: Implement `getDrupalSearchResults` Function
  .changeset/real-chicken-taste.md
  .changeset/red-crabs-sort.md
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal-search-api-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/app/layout.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/app/search-input.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/app/search/page.js
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/components/search-input.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/next.config.js.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/pages/search/[[...alias]].jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/tailwind.config.js
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/__tests__/setupFile.js
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-drupal/nextDrupalLayout.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-drupal/sharedNextDrupalConfig.hbs
  packages/drupal-kit/src/__tests__/data/exampleSearchResultsAltIndex.json
  packages/drupal-kit/src/__tests__/data/exampleSearchResultsDefaultIndex.json
  packages/drupal-kit/src/__tests__/getDrupalSearchResults.test.ts
  packages/drupal-kit/src/lib/getDrupalSearchResults.ts
  packages/drupal-kit/src/lib/index.ts
Labels: cli, cli-addon

#617 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
Labels: 🐥 canary release

#620 DB-5804: update WordPress build hooks entry to prevent duplicate hook submissions
  web/docs/Backend Starters/Decoupled WordPress/configuring-build-hooks.md
Labels: documentation

#608 DB-5713: Search Term Persistence
  .changeset/swift-dogs-care.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/components/search-input.jsx
Labels: cli, cli-addon

#622 DB-5693: Adjust Add-on Formatting to Satisfy Lint
  .changeset/funny-owls-build.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/post.jsx
Labels: cli, cli-addon

#624 Exit pre-release mode for sprint 7
  .changeset/pre.json
Labels: release

#627 Add --tailwindcss flag to next-drupal-starter release split cmd
  .github/workflows/release-and-split.yml
Labels: ci/cd, bugfix

#629 Sprint 7 Backmerge Main -> Canary
  .changeset/funny-owls-build.md
  .changeset/gold-humans-begin.md
  .changeset/hip-oranges-whisper.md
  .changeset/pre.json
  .changeset/real-chicken-taste.md
  .changeset/red-crabs-sort.md
  .changeset/swift-dogs-care.md
  .changeset/violet-horses-carry.md
  .changeset/young-brooms-argue.md
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
Labels: release

#630 Enter prerelease mode for sprint 8
  .changeset/pre.json
Labels: release

#619 DB-5716: Search Results Route
  .changeset/dirty-rats-share.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/app/layout.module.css.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/pages/search/[[...alias]].jsx
Labels: cli, cli-addon

#633 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#634 DB-5693: Starter Kit ACF Adjustments
  .changeset/fluffy-suits-knock.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/post.jsx
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-wp/nextWpPostView.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-wp/nextWpPostsJS.hbs
Labels: cli, cli-addon

#635 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#618 DB-5719: Add-on docs for Decoupled Kit Pantheon Search API module.
  web/docs/Backend Starters/Decoupled Drupal/add-ons.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-build-hooks.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-existing-project.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md
Labels: documentation

#632 DB-5572: [cli] Prompt for cmsEndpoint
  .changeset/shaggy-rockets-thank.md
  packages/create-pantheon-decoupled-kit/__tests__/handlebarsHelpers.test.ts
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal-search-api-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal-umami-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/tailwindcss-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/.env.development.local.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/.env.development.local.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/.env.development.local.hbs
  packages/create-pantheon-decoupled-kit/src/utils/handlebars.ts
  packages/create-pantheon-decoupled-kit/src/utils/helpMenu.ts
  packages/create-pantheon-decoupled-kit/src/utils/sharedPrompts.ts
  packages/create-pantheon-decoupled-kit/watch.example.ts
  web/docs/Frontend Starters/create-pantheon-decoupled-kit.md
Labels: cli

#638 Omit cmsEndpoint in generator_cmd
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd

#636 DB-5716: Escape Characters in Search Queries
  .changeset/polite-suns-look.md
  packages/drupal-kit/src/lib/getDrupalSearchResults.ts
Labels: drupal-kit

#639 [docs] Docs update npm init
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/intro.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/intro.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/intro.md
  web/docs/Frontend Starters/create-pantheon-decoupled-kit.md
  web/docs/Packages/cms-kit/modules.md
  web/docs/Packages/create-pantheon-decoupled-kit/index.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DecoupledKitGenerator.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DefaultAnswers.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/TemplateData.md
  web/docs/Packages/create-pantheon-decoupled-kit/modules.md
  web/docs/Packages/drupal-kit/classes/DrupalState.md
  web/docs/Packages/drupal-kit/interfaces/authInit.md
  web/docs/Packages/drupal-kit/modules.md
  web/docs/Packages/nextjs-kit/interfaces/ContentProps.md
  web/docs/Packages/nextjs-kit/interfaces/FooterMenuProps.md
  web/docs/Packages/nextjs-kit/interfaces/HeaderProps.md
  web/docs/Packages/nextjs-kit/interfaces/LinkProps.md
  web/docs/Packages/nextjs-kit/interfaces/PaginationProps.md
  web/docs/Packages/nextjs-kit/interfaces/PreviewRibbonProps.md
  web/docs/Packages/nextjs-kit/interfaces/RecipeProps.md
  web/docs/Packages/nextjs-kit/interfaces/SortOptions.md
  web/docs/Packages/nextjs-kit/modules.md
Labels: documentation

#641 DB-5914: Fix GraphQLFactory options type
  .changeset/olive-wolves-call.md
  .changeset/weak-dragons-agree.md
  packages/wordpress-kit/src/lib/graphqlClient/GraphqlClientFactory.ts
  web/docs/Packages/wordpress-kit/classes/GraphqlClientFactory.md
Labels: documentation, bugfix, wordpress-kit

#640 DB-5758: Search Box Refinements
  .changeset/popular-dingos-search.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/components/search-input.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/pages/search/[[...alias]].jsx
  packages/create-pantheon-decoupled-kit/src/templates/partials/next-drupal/nextDrupalLayout.hbs
Labels: next-drupal, cli, cli-addon

#643 Fix changesets
  .changeset/dirty-rats-share.md
  .changeset/olive-wolves-call.md
Labels: bug

#642 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
Labels: 🐥 canary release

#645 DB-5574: getObject generic
  .changeset/clever-ties-smile.md
  .changeset/light-socks-protect.md
  .changeset/perfect-dolphins-relax.md
  .husky/pre-commit
  packages/cms-kit/src/utils/setSurrogateKeyHeader.ts
  packages/drupal-kit/src/lib/PantheonDrupalState.ts
  scripts/generate-starters.ts
Labels: decoupled-kit, drupal-kit, cms-kit

#648 Nightly Audit on 04/25/23
  package.json
  pnpm-lock.yaml
Labels: security, dependencies

#646 Canary Release (canary)
  .changeset/pre.json
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
Labels: 🐥 canary release

#650 Exit pre-release mode for sprint 8
  .changeset/pre.json
Labels: release

#655 Enter pre-release mode for sprint 9
  .changeset/pre.json
Labels: release

#647 DB-5773: CMS Type Option
  .changeset/large-tips-crash.md
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal-search-api-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal-umami-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/tailwindcss-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/types.ts
  packages/create-pantheon-decoupled-kit/src/utils/helpMenu.ts
Labels: cli, cli-base

#651 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#656 DB-5908: Include Proper Tailwindcss Deps in `wordpress-kit`
  .changeset/cyan-colts-lay.md
  .changeset/smooth-bees-pretend.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/pkg-shared/tailwindcssDeps.hbs
  packages/wordpress-kit/package.json
  pnpm-lock.yaml
Labels: wordpress-kit, cli, cli-base

#657 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
Labels: 🐥 canary release

#658 Refactor overview doc section on creating a new starter
  packages/create-pantheon-decoupled-kit/README.md
  web/docs/decoupled-kit-overview.md
Labels: documentation
