Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-03, with the labels that each got.

#555 DB-5253: Fix missing gitignore template when published to npm
  .changeset/unlucky-birds-eat.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/.npmignore
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-umami-addon/.gitignore
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/.npmignore
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/.npmignore
Labels: bugfix, cli

#557 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#556 Exit pre-release mode for sprint 4
  .changeset/pre.json
Labels: release

#560 Decoupled Kit Sprint 4: Update versions
  .changeset/pre.json
  .changeset/short-starfishes-taste.md
  .changeset/spotty-dodos-sip.md
  .changeset/three-meals-carry.md
  .changeset/tiny-eyes-drum.md
  .changeset/unlucky-birds-eat.md
  .changeset/wild-mails-work.md
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: release

#563 Enter pre-release mode for sprint 5
  .changeset/pre.json
Labels: release

#514 Nightly Audit on 02/10/23
  package.json
  pnpm-lock.yaml
Labels: security, dependencies

#558 Canary Release (canary)
  .changeset/pre.json
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/configs/eslint/CHANGELOG.md
  packages/configs/eslint/package.json
  packages/configs/other/CHANGELOG.md
  packages/configs/other/package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: 🐥 canary release

#564 DB-5253: Use CLI to generate starters for mirrors
  .github/workflows/canary-release.yml
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
  README.md
  web/docs/contributing.md
Labels: ci/cd

#567 DB-5402: Add-on docs for Advanced Custom Fields.
  web/docs/Backend Starters/Decoupled WordPress/add-ons.md
  web/docs/Backend Starters/Decoupled WordPress/caching-considerations.md
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/add-ons.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/add-ons.md
Labels: documentation

#566 DB-5058: CLI docs and updated API reference
  CONTRIBUTING.md
  web/docs/Frontend Starters/Gatsby/_category_.json
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/add-ons.md
  web/docs/Frontend Starters/Next.js/_category_.json
  web/docs/Frontend Starters/create-pantheon-decoupled-kit.md
  web/docs/Packages/create-pantheon-decoupled-kit/index.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DecoupledKitGenerator.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DefaultAnswers.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/MergedPaths.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/TemplateData.md
  web/docs/Packages/create-pantheon-decoupled-kit/modules.md
Labels: documentation

#568 DB-5253: Fix workflow files output repo
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd, bugfix

#570 DB-5253: Use rename strategy for gitignore template
  .changeset/six-lamps-kiss.md
  packages/create-pantheon-decoupled-kit/__tests__/addWithDiff.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/fixtures/addWithDiff/populated/.gitignore
  packages/create-pantheon-decoupled-kit/__tests__/templates/addWithDiff/gitignore
  packages/create-pantheon-decoupled-kit/src/actions/addWithDiff.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/gitignore
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/gitignore
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/gitignore
Labels: bugfix, cli

#569 DB-5495: Add Published `eslint` Configs to Gatsby Generator
  .changeset/rude-yaks-wonder.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/.eslintrc
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/src/components/seo.jsx
Labels: gatsby-wordpress, cli, cli-base

#571 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#572 DB-5253: Fix for conditional action
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd, bugfix

#573 DB-5253: Try to fix GH Action conditional
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd, bugfix

#574 Add conditional for gatsby-plugin-pnpm in gastby-config
  .changeset/red-kings-help.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/gatsby-config.js.hbs
Labels: gatsby-wordpress, bugfix, cli, cli-base

#575 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#576 DB-5385: Watch script refinements
  .changeset/mean-buckets-perform.md
  packages/create-pantheon-decoupled-kit/__tests__/actionRunner.test.ts
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/scripts/watchTemplates.ts
  packages/create-pantheon-decoupled-kit/src/actions/addWithDiff.ts
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/utils/actionRunner.ts
  packages/create-pantheon-decoupled-kit/src/utils/dedupeTemplates.ts
  packages/create-pantheon-decoupled-kit/watch.example.ts
  pnpm-lock.yaml
Labels: cli

#578 Remove .npmignores from project templates
  .changeset/wise-impalas-yawn.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/.npmignore
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/.npmignore
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/.npmignore
Labels: cli, cli-base

#580 Dependency audit and some typo fixes
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/add-ons.md
Labels: documentation, decoupled-kit, security

#577 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#581 DB-5636: Ensure latest versions are published
  package.json
  scripts/ci-version
Labels: ci/cd

#582 Exit pre-release mode for sprint 5
  .changeset/pre.json
Labels: release

#585 Update versions
  .changeset/curly-glasses-deny.md
  .changeset/five-windows-taste.md
  .changeset/little-pillows-tell.md
  .changeset/mean-buckets-perform.md
  .changeset/popular-news-argue.md
  .changeset/pre.json
  .changeset/red-kings-help.md
  .changeset/rude-spoons-bow.md
  .changeset/rude-yaks-wonder.md
  .changeset/sharp-crabs-kiss.md
  .changeset/six-lamps-kiss.md
  .changeset/thick-cougars-jog.md
  .changeset/violet-pots-refuse.md
  .changeset/weak-donuts-tap.md
  .changeset/wise-impalas-yawn.md
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/configs/eslint/CHANGELOG.md
  packages/configs/eslint/package.json
  packages/configs/other/CHANGELOG.md
  packages/configs/other/package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#587 Sprint 5: main -> canary
  .changeset/curly-glasses-deny.md
  .changeset/five-windows-taste.md
  .changeset/little-pillows-tell.md
  .changeset/mean-buckets-perform.md
  .changeset/popular-news-argue.md
  .changeset/pre.json
  .changeset/red-kings-help.md
  .changeset/rude-spoons-bow.md
  .changeset/rude-yaks-wonder.md
  .changeset/sharp-crabs-kiss.md
  .changeset/six-lamps-kiss.md
  .changeset/thick-cougars-jog.md
  .changeset/violet-pots-refuse.md
  .changeset/weak-donuts-tap.md
  .changeset/wise-impalas-yawn.md
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/configs/eslint/CHANGELOG.md
  packages/configs/eslint/package.json
  packages/configs/other/CHANGELOG.md
  packages/configs/other/package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#588 Enter pre-release for sprint 6
  .changeset/pre.json
Labels: release

#589 DB-5055: tailwindcss addon
  .changeset/proud-eels-dress.md
  packages/create-pantheon-decoupled-kit/__tests__/actionRunner.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/addDependencies.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/templates/addDependencies/.gitkeep
  packages/create-pantheon-decoupled-kit/src/actions/addDependencies.ts
  packages/create-pantheon-decoupled-kit/src/actions/index.ts
  packages/create-pantheon-decoupled-kit/src/actions/runInstall.ts
  packages/create-pantheon-decoupled-kit/src/generators/index.ts
  packages/create-pantheon-decoupled-kit/src/generators/tailwindcss-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/tailwindcss-addon/postcss.config.cjs
  packages/create-pantheon-decoupled-kit/src/templates/tailwindcss-addon/styles/globals.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindcss-addon/tailwind.config.cjs
  packages/create-pantheon-decoupled-kit/src/types.ts
  web/docs/Frontend Starters/create-pantheon-decoupled-kit.md
Labels: documentation, cli

#586 DB-5252: Update READMEs to use `npm init` as the default way to create a project
  .changeset/weak-beers-talk.md
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md
  starters/gatsby-wordpress-starter/README.md
  starters/next-drupal-starter/README.md
  starters/next-wordpress-starter/README.md
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/intro.md
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/setting-environment-variables.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/intro.md
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/setting-environment-variables.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/intro.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-environment-variables.md
Labels: next-drupal, gatsby-wordpress, next-wordpress, cli

#590 DB-5712: Add CSR Search Input to `/pages` Layout
  .changeset/long-yaks-lie.md
  packages/create-pantheon-decoupled-kit/src/generators/index.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal-search-api-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/[...alias].test.jsx.snap
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/articles.test.jsx.snap
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/auth-api.test.jsx.snap
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/examples-index.test.jsx.snap
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/homepage.test.jsx.snap
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/pages.test.jsx.snap
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/pagination.test.jsx.snap
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/__snapshots__/ssr-isr-example.test.jsx.snap
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/snapshotTests/auth-api.test.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/__tests__/snapshotTests/homepage.test.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/components/layout.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal-search-api-addon/components/search-input.jsx
Labels: cli

#594 DB-5060: refine contributing to cli docs and generator generics
  .changeset/fair-emus-accept.md
  CONTRIBUTING.md
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/index.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal-search-api-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal-umami-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/tailwindcss-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/types.ts
  packages/create-pantheon-decoupled-kit/src/utils/helpMenu.ts
Labels: documentation, cli

#592 DB-5227: tailwindless next-wp (part 1)
  .changeset/late-hornets-invent.md
  .prettierignore
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/src/actions/addWithDiff.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/lib/Posts.js
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/lib/Posts.js.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/pages/pages/[...uri].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/pages/posts/[...slug].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/pages/posts/[...slug].module.css.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/components/grid.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/components/grid.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/components/layout.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/components/page-header.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/components/page-header.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/lib/Posts.js.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/404.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/404.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/500.jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/500.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/examples/auth-api.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/examples/index.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/examples/pagination/[[...page]].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/examples/ssg-isr.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/index.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/pages/[...uri].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/pages/index.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/posts/[...slug].jsx
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/posts/[...slug].jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/pages/posts/index.jsx.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/nextWpPageView.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/nextWpPostCSS.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/nextWpPostView.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/nextWpPostsJS.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/tailwindcssDeps.hbs
  packages/create-pantheon-decoupled-kit/src/templates/tailwind-shared/postcss.config.cjs
  packages/create-pantheon-decoupled-kit/src/templates/tailwind-shared/styles/globals.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwind-shared/tailwind.config.cjs.hbs
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/components/grid.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/components/layout.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/components/page-header.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/404.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/500.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/examples/auth-api.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/examples/index.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/examples/pagination/pagination.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/examples/ssg-isr.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/index.module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/pages/[...uri].module.css
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/pages/posts/[...slug].module.css.hbs
  packages/create-pantheon-decoupled-kit/src/templates/tailwindless-next/styles/globals.css
Labels: next-wordpress, cli

#591 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#595 Add tailwindcss flag to next-wp generator_commands
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd, bugfix

#596 DB-5227: Fix missing dependency
  .changeset/chilled-icons-obey.md
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/tailwindcssDeps.hbs
Labels: bugfix, cli

#597 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#601 Sprint 6: Update versions
  .changeset/angry-suns-rest.md
  .changeset/chilled-icons-obey.md
  .changeset/fair-emus-accept.md
  .changeset/late-hornets-invent.md
  .changeset/long-yaks-lie.md
  .changeset/pre.json
  .changeset/proud-eels-dress.md
  .changeset/weak-beers-talk.md
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: release

#603 Enter pre-release mode for sprint 7
  .changeset/pre.json
Labels: release
