Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-02, with the labels that each got.

#496 Upgrade to latest monorepo split action release
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
Labels: release

#497 Update monorepo split version and commit username
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
Labels: release

#498 Correct the tag reference for monorepo split action
  .github/workflows/canary-sites-split.yml
  .github/workflows/release-and-split.yml
Labels: release

#500 Update versions
  .changeset/cool-wasps-burn.md
  .changeset/grumpy-jokes-clean.md
  .changeset/happy-moose-try.md
  .changeset/hip-ladybugs-care.md
  .changeset/kind-chairs-camp.md
  .changeset/kind-crabs-behave.md
  .changeset/pre.json
  .changeset/thin-fans-approve.md
  .changeset/tidy-ligers-crash.md
  .changeset/tough-guests-call.md
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#501 Sprint 3: backmerge canary -> main
  .changeset/cool-wasps-burn.md
  .changeset/grumpy-jokes-clean.md
  .changeset/happy-moose-try.md
  .changeset/hip-ladybugs-care.md
  .changeset/kind-chairs-camp.md
  .changeset/kind-crabs-behave.md
  .changeset/pre.json
  .changeset/thin-fans-approve.md
  .changeset/tidy-ligers-crash.md
  .changeset/tough-guests-call.md
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  starters/gatsby-wordpress-starter/CHANGELOG.md
  starters/gatsby-wordpress-starter/package.json
  starters/next-drupal-starter/CHANGELOG.md
  starters/next-drupal-starter/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: release

#502 Enter prerelease mode for sprint 3
  .changeset/pre.json
Labels: release

#489 DB-5237: Support GraphQL Over HTTP `GET`
  .changeset/modern-queens-complain.md
  .changeset/sharp-donuts-judge.md
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/README.md
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/lib/WordPressClient.js
  starters/next-wordpress-starter/README.md
  starters/next-wordpress-starter/lib/WordPressClient.js
Labels: next-wordpress

#495 Nightly Audit on 02/01/23
  package.json
  pnpm-lock.yaml
Labels: security

#504 Nightly Audit on 02/02/23
  package.json
  pnpm-lock.yaml
Labels: security, dependencies

#505 Fix build:next-wp script
  package.json
Labels: decoupled-kit, bugfix

#494 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  starters/next-wordpress-starter/CHANGELOG.md
  starters/next-wordpress-starter/package.json
Labels: 🐥 canary release

#509 DB-5059: Add docs for developing with the cli
  CONTRIBUTING.md
  packages/create-pantheon-decoupled-kit/README.md
  packages/create-pantheon-decoupled-kit/index.ts
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/src/utils/index.ts
  packages/create-pantheon-decoupled-kit/watch.example.ts
  web/docs/Packages/create-pantheon-decoupled-kit/index.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DecoupledKitGenerator.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/_category_.yml
  web/docs/Packages/create-pantheon-decoupled-kit/modules.md
  web/docusaurus.config.js
Labels: documentation

#511 Upgrade pnpm to fix `pnpm config` in CI
  .circleci/config.yml
  README.md
  package.json
  pnpm-lock.yaml
  web/docs/contributing.md
Labels: decoupled-kit, ci/cd, dependencies

#512 DB-5376: Update Default Cache Control Values
  .changeset/hip-seas-beam.md
  packages/drupal-kit/src/__tests__/PantheonDrupalState.test.ts
  packages/drupal-kit/src/lib/defaultFetch.ts
  packages/wordpress-kit/__tests__/setEdgeHeader.test.ts
  packages/wordpress-kit/src/lib/setEdgeHeader.ts
  web/docs/Frontend Starters/Next.js/Next.js + Drupal/setting-cache-control-header.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/setting-cache-control-header.md
  web/docs/Packages/drupal-kit/modules.md
Labels: drupal-kit, wordpress-kit

#515 DB-5253: Part 1 - initial cleanup
  .changeset/mighty-socks-deny.md
  CHANGELOG.md
  packages/create-pantheon-decoupled-kit/__mocks__/node-plop.ts
  packages/create-pantheon-decoupled-kit/__tests__/addWithDiff.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/handlebarsHelpers.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/runESLint.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/runInstall.test.ts
  packages/create-pantheon-decoupled-kit/index.ts
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/src/actions/addWithDiff.ts
  packages/create-pantheon-decoupled-kit/src/actions/index.ts
  packages/create-pantheon-decoupled-kit/src/actions/runESLint.ts
  packages/create-pantheon-decoupled-kit/src/actions/runInstall.ts
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-drupal/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/next-wp/package.json.hbs
  packages/create-pantheon-decoupled-kit/src/templates/partials/.gitkeep
  packages/create-pantheon-decoupled-kit/src/templates/partials/sharedPkgJsonFields.hbs
  packages/create-pantheon-decoupled-kit/src/types.ts
  packages/create-pantheon-decoupled-kit/src/utils/handlebarsHelpers.ts
  packages/create-pantheon-decoupled-kit/src/utils/helpMenu.ts
  packages/create-pantheon-decoupled-kit/src/utils/index.ts
  web/docs/Packages/create-pantheon-decoupled-kit/index.md
  web/docs/Packages/create-pantheon-decoupled-kit/interfaces/DecoupledKitGenerator.md
  web/docs/Packages/create-pantheon-decoupled-kit/modules.md
Labels: cli

#510 DB-940: Document Build Hooks Configuration.
  web/docs/Backend Starters/Decoupled Drupal/configuring-build-hooks.md
  web/static/img/drupal-trigger-deployment-manually.gif
Labels: documentation

#524 Exit pre-release mode for sprint 3
  .changeset/pre.json
Labels: release

#530 Enter pre-release for sprint 4
  .changeset/pre.json
Labels: release

#537 DB-5403: `next-wp` Related Content ACF Component Addon
  .changeset/wild-mails-work.md
  packages/create-pantheon-decoupled-kit/src/generators/index.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/lib/Posts.js
  packages/create-pantheon-decoupled-kit/src/templates/next-wp-acf-addon/pages/posts/[...slug].jsx
Labels: cli

#539 DB-5404: `gatsby-wp` Related Content ACF Component Addon
  .changeset/spotty-dodos-sip.md
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/index.ts
  packages/create-pantheon-decoupled-kit/src/templates/gatsby-wp-acf-addon/src/templates/post.jsx
Labels: gatsby-wordpress, cli, cli-addon

#525 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#541 DB-4186: Document how to emit cache-control headers for caching API calls
  web/docs/Backend Starters/Decoupled Drupal/caching-considerations.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-build-hooks.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-existing-project.md
  web/docs/Backend Starters/Decoupled Drupal/configuring-preview-site.md
  web/docs/Backend Starters/Decoupled Drupal/cors.md
Labels: documentation

#543 DB-5240: loose ends for GraphQL Caching Docs
  web/docs/Backend Starters/Decoupled WordPress/caching-considerations.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/surrogate-key-based-caching.md
Labels: documentation

#547 DB-5507-DB-5509: Refactor to remove node-plop
  .changeset/tiny-eyes-drum.md
  packages/create-pantheon-decoupled-kit/README.md
  packages/create-pantheon-decoupled-kit/__mocks__/node-plop.ts
  packages/create-pantheon-decoupled-kit/__tests__/actionRunner.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/addWithDiff.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/fixtures/addWithDiff/populated/test-binaryFile.png
  packages/create-pantheon-decoupled-kit/__tests__/handlebarsHelpers.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/index.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/runInstall.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/runLint.test.ts
  packages/create-pantheon-decoupled-kit/__tests__/templates/addWithDiff/test-anotherFileWithDiff.js.hbs
  packages/create-pantheon-decoupled-kit/__tests__/templates/addWithDiff/test-binaryFile.png
  packages/create-pantheon-decoupled-kit/__tests__/templates/addWithDiff/test-toBeCopiedWithDiff.json
  packages/create-pantheon-decoupled-kit/__tests__/templates/addWithDiff/test-withDiff.js.hbs
  packages/create-pantheon-decoupled-kit/__tests__/templates/partials/testPartial.hbs
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/generators/index.ts
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/generators/test-append.generator.ts
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/generators/test.generator.ts
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/templates/test/testAdd/test-template.js.hbs
  packages/create-pantheon-decoupled-kit/__tests__/testGenerators/templates/test/testAppend/test-template.js.hbs
  packages/create-pantheon-decoupled-kit/esbuild.js
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/src/actions/addWithDiff.ts
  packages/create-pantheon-decoupled-kit/src/actions/index.ts
  packages/create-pantheon-decoupled-kit/src/actions/runESLint.ts
  packages/create-pantheon-decoupled-kit/src/actions/runInstall.ts
  packages/create-pantheon-decoupled-kit/src/actions/runLint.ts
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/gatsby-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/index.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal-umami-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-drupal.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp-acf-addon.generator.ts
  packages/create-pantheon-decoupled-kit/src/generators/next-wp.generator.ts
  packages/create-pantheon-decoupled-kit/src/index.ts
  packages/create-pantheon-decoupled-kit/src/types.ts
  packages/create-pantheon-decoupled-kit/src/utils/actionRunner.ts
  packages/create-pantheon-decoupled-kit/src/utils/dedupeTemplates.ts
  packages/create-pantheon-decoupled-kit/src/utils/getPartials.ts
  packages/create-pantheon-decoupled-kit/src/utils/handlebars.ts
  packages/create-pantheon-decoupled-kit/src/utils/handlebarsHelpers.ts
  packages/create-pantheon-decoupled-kit/src/utils/helpMenu.ts
  packages/create-pantheon-decoupled-kit/src/utils/index.ts
  pnpm-lock.yaml
Labels: cli

#545 DB-5455: Advanced Custom Fields Add-on Docs
  web/docs/Frontend Starters/Gatsby/Gatsby + WordPress/add-ons.md
  web/docs/Frontend Starters/Next.js/Next.js + WordPress/add-ons.md
Labels: documentation

#551 Canary Release (canary)
  .changeset/pre.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
Labels: 🐥 canary release

#552 Fix missing dependency
  .changeset/short-starfishes-taste.md
  packages/create-pantheon-decoupled-kit/package.json
  pnpm-lock.yaml
Labels: bugfix, cli

#506 [CMSO-1248] Draft instructions for updating to Drupal 10
  web/docs/Backend Starters/Decoupled Drupal/creating-new-project.md
Labels: documentation
