Repository pantheon-systems/decoupled-kit-js, pull requests merged in 2023-12, with the labels that each got.

#973 Sprint 23: Main -> Canary
  .changeset/big-keys-live.md
  .changeset/pre.json
  .changeset/shy-toys-know.md
  .changeset/tender-geckos-smash.md
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/decoupled-kit-health-check/CHANGELOG.md
  packages/decoupled-kit-health-check/package.json
Labels: release

#974 Enter pre-release mode for sprint 24
  .changeset/pre.json
Labels: release

#977 KIT-93: [react-kit] `<Footer />` component
  .changeset/curly-lobsters-battle.md
  packages/react-kit/__tests__/snapshotTests/Footer.test.tsx
  packages/react-kit/__tests__/snapshotTests/__snapshots__/Footer.test.tsx.snap
  packages/react-kit/src/assets/pantheon-fist-white.svg
  packages/react-kit/src/components/Footer/Footer.stories.tsx
  packages/react-kit/src/components/Footer/Footer.tsx
  packages/react-kit/src/components/Footer/index.tsx
  packages/react-kit/src/components/Footer/props.ts
Labels: documentation, react-kit

#984 KIT-142: Fix gatsby develop infinite re-render
  .changeset/calm-countries-roll.md
  packages/create-pantheon-decoupled-kit/src/templates/tailwind-shared/tailwind.config.cjs.hbs
Labels: gatsby-wordpress, bugfix, cli-templates

#985 KIT-173: Use GHA instead of CircleCI for test job
  .circleci/config.yml
  .github/workflows/run-tests.yml
  README.md
  pnpm-lock.yaml
Labels: ci/cd

#990 Consolidate deps to monorepo root, update some deps
  .changeset/rude-buckets-remember.md
  package.json
  packages/cms-kit/package.json
  packages/cms-kit/vite.config.mts
  packages/create-pantheon-decoupled-kit/esbuild.js
  packages/create-pantheon-decoupled-kit/package.json
  packages/create-pantheon-decoupled-kit/tsconfig.json
  packages/create-pantheon-decoupled-kit/tsconfig.typedoc.json
  packages/create-pantheon-decoupled-kit/vite.config.mts
  packages/decoupled-kit-health-check/package.json
  packages/decoupled-kit-health-check/tsconfig.json
  packages/decoupled-kit-health-check/vite.config.mts
  packages/drupal-kit/package.json
  packages/drupal-kit/vite.config.mts
  packages/nextjs-kit/package.json
  packages/nextjs-kit/vite.config.mts
  packages/react-kit/package.json
  packages/react-kit/vite.config.mts
  packages/wordpress-kit/package.json
  packages/wordpress-kit/vite.config.mts
  pnpm-lock.yaml
Labels: decoupled-kit, dependencies

#992 Add storybook to root package.json
  package.json
  pnpm-lock.yaml
Labels: dependencies

#993 Do not persist credentials for release checkouts
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd

#994 Try checkout with token to enable workflows on changeset branches
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
Labels: ci/cd

#996 Revert back to circleci for ci tests
  .circleci/config.yml
  .github/workflows/canary-release.yml
  .github/workflows/release-and-split.yml
  .github/workflows/run-tests.yml
Labels: ci/cd

#1004 Update changeset
  .changeset/rude-buckets-remember.md
Labels: bugfix

#1005 Remove setupgituser
  .github/workflows/release-and-split.yml
Labels: bugfix

#1007 Sprint 24: Backmerge Main -> Canary
  .changeset/calm-countries-roll.md
  .changeset/eighty-buttons-walk.md
  .changeset/pre.json
  .changeset/rude-buckets-remember.md
  .github/workflows/release-and-split.yml
  configs/eslint/CHANGELOG.md
  configs/eslint/package.json
  packages/cms-kit/CHANGELOG.md
  packages/cms-kit/package.json
  packages/configs/eslint/CHANGELOG.md
  packages/configs/eslint/package.json
  packages/configs/other/CHANGELOG.md
  packages/configs/other/package.json
  packages/create-pantheon-decoupled-kit/CHANGELOG.md
  packages/create-pantheon-decoupled-kit/package.json
  packages/decoupled-kit-health-check/CHANGELOG.md
  packages/decoupled-kit-health-check/package.json
  packages/drupal-kit/CHANGELOG.md
  packages/drupal-kit/package.json
  packages/nextjs-kit/CHANGELOG.md
  packages/nextjs-kit/package.json
  packages/react-kit/CHANGELOG.md
  packages/react-kit/package.json
  packages/wordpress-kit/CHANGELOG.md
  packages/wordpress-kit/package.json
Labels: release
